//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Business.eTranzactWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.etz.com/", ConfigurationName="eTranzactWebService.QueryPayoutletTransaction")]
    public interface QueryPayoutletTransaction {
        
        // CODEGEN: Generating message contract since the operation queryPayoutletTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse1 queryPayoutletTransaction(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse1> queryPayoutletTransactionAsync(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.etz.com/")]
    public partial class queryPayoutletTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string terminalIdField;
        
        private string confirmationNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string terminalId {
            get {
                return this.terminalIdField;
            }
            set {
                this.terminalIdField = value;
                this.RaisePropertyChanged("terminalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string confirmationNo {
            get {
                return this.confirmationNoField;
            }
            set {
                this.confirmationNoField = value;
                this.RaisePropertyChanged("confirmationNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.etz.com/")]
    public partial class queryPayoutletTransactionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryPayoutletTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.etz.com/", Order=0)]
        public Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransaction queryPayoutletTransaction;
        
        public queryPayoutletTransactionRequest() {
        }
        
        public queryPayoutletTransactionRequest(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransaction queryPayoutletTransaction) {
            this.queryPayoutletTransaction = queryPayoutletTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryPayoutletTransactionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.etz.com/", Order=0)]
        public Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse queryPayoutletTransactionResponse;
        
        public queryPayoutletTransactionResponse1() {
        }
        
        public queryPayoutletTransactionResponse1(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse queryPayoutletTransactionResponse) {
            this.queryPayoutletTransactionResponse = queryPayoutletTransactionResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QueryPayoutletTransactionChannel : Abundance_Nk.Business.eTranzactWebService.QueryPayoutletTransaction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryPayoutletTransactionClient : System.ServiceModel.ClientBase<Abundance_Nk.Business.eTranzactWebService.QueryPayoutletTransaction>, Abundance_Nk.Business.eTranzactWebService.QueryPayoutletTransaction {
        
        public QueryPayoutletTransactionClient() {
        }
        
        public QueryPayoutletTransactionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryPayoutletTransactionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryPayoutletTransactionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryPayoutletTransactionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse1 Abundance_Nk.Business.eTranzactWebService.QueryPayoutletTransaction.queryPayoutletTransaction(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest request) {
            return base.Channel.queryPayoutletTransaction(request);
        }
        
        public Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse queryPayoutletTransaction(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransaction queryPayoutletTransaction1) {
            Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest inValue = new Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest();
            inValue.queryPayoutletTransaction = queryPayoutletTransaction1;
            Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse1 retVal = ((Abundance_Nk.Business.eTranzactWebService.QueryPayoutletTransaction)(this)).queryPayoutletTransaction(inValue);
            return retVal.queryPayoutletTransactionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse1> Abundance_Nk.Business.eTranzactWebService.QueryPayoutletTransaction.queryPayoutletTransactionAsync(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest request) {
            return base.Channel.queryPayoutletTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionResponse1> queryPayoutletTransactionAsync(Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransaction queryPayoutletTransaction) {
            Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest inValue = new Abundance_Nk.Business.eTranzactWebService.queryPayoutletTransactionRequest();
            inValue.queryPayoutletTransaction = queryPayoutletTransaction;
            return ((Abundance_Nk.Business.eTranzactWebService.QueryPayoutletTransaction)(this)).queryPayoutletTransactionAsync(inValue);
        }
    }
}
