//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Abundance_NkEntities : DbContext
    {
        public Abundance_NkEntities()
            : base("name=Abundance_NkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABILITY> ABILITY { get; set; }
        public virtual DbSet<ACADEMIC_STANDING> ACADEMIC_STANDING { get; set; }
        public virtual DbSet<ADMISSION_CRITERIA> ADMISSION_CRITERIA { get; set; }
        public virtual DbSet<ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT> ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT { get; set; }
        public virtual DbSet<ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT_ALTERNATIVE> ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT_ALTERNATIVE { get; set; }
        public virtual DbSet<ADMISSION_CRITERIA_FOR_O_LEVEL_TYPE> ADMISSION_CRITERIA_FOR_O_LEVEL_TYPE { get; set; }
        public virtual DbSet<ADMISSION_LIST> ADMISSION_LIST { get; set; }
        public virtual DbSet<ADMISSION_LIST_AUDIT> ADMISSION_LIST_AUDIT { get; set; }
        public virtual DbSet<ADMISSION_LIST_BATCH> ADMISSION_LIST_BATCH { get; set; }
        public virtual DbSet<ADMISSION_LIST_TYPE> ADMISSION_LIST_TYPE { get; set; }
        public virtual DbSet<APPLICANT> APPLICANT { get; set; }
        public virtual DbSet<APPLICANT_APPLIED_COURSE> APPLICANT_APPLIED_COURSE { get; set; }
        public virtual DbSet<APPLICANT_APPLIED_COURSE_AUDIT> APPLICANT_APPLIED_COURSE_AUDIT { get; set; }
        public virtual DbSet<APPLICANT_CLEARANCE> APPLICANT_CLEARANCE { get; set; }
        public virtual DbSet<APPLICANT_JAMB_DETAIL> APPLICANT_JAMB_DETAIL { get; set; }
        public virtual DbSet<APPLICANT_LEVEL> APPLICANT_LEVEL { get; set; }
        public virtual DbSet<APPLICANT_O_LEVEL_RESULT> APPLICANT_O_LEVEL_RESULT { get; set; }
        public virtual DbSet<APPLICANT_O_LEVEL_RESULT_AUDIT> APPLICANT_O_LEVEL_RESULT_AUDIT { get; set; }
        public virtual DbSet<APPLICANT_O_LEVEL_RESULT_DETAIL> APPLICANT_O_LEVEL_RESULT_DETAIL { get; set; }
        public virtual DbSet<APPLICANT_O_LEVEL_RESULT_DETAIL_AUDIT> APPLICANT_O_LEVEL_RESULT_DETAIL_AUDIT { get; set; }
        public virtual DbSet<APPLICANT_SPONSOR> APPLICANT_SPONSOR { get; set; }
        public virtual DbSet<APPLICANT_STATUS> APPLICANT_STATUS { get; set; }
        public virtual DbSet<APPLICATION_FORM> APPLICATION_FORM { get; set; }
        public virtual DbSet<APPLICATION_FORM_SETTING> APPLICATION_FORM_SETTING { get; set; }
        public virtual DbSet<APPLICATION_PROGRAMME_FEE> APPLICATION_PROGRAMME_FEE { get; set; }
        public virtual DbSet<ATTENDANCE> ATTENDANCE { get; set; }
        public virtual DbSet<ATTENDANCE_STATUS> ATTENDANCE_STATUS { get; set; }
        public virtual DbSet<BANK> BANK { get; set; }
        public virtual DbSet<BANK_BRANCH> BANK_BRANCH { get; set; }
        public virtual DbSet<BLOOD_GROUP> BLOOD_GROUP { get; set; }
        public virtual DbSet<CARD_PAYMENT> CARD_PAYMENT { get; set; }
        public virtual DbSet<CHANGE_OF_COURSE> CHANGE_OF_COURSE { get; set; }
        public virtual DbSet<CLASS_ASSESSMENT> CLASS_ASSESSMENT { get; set; }
        public virtual DbSet<CLASS_ROOM> CLASS_ROOM { get; set; }
        public virtual DbSet<CLEARANCE_DISPUTES> CLEARANCE_DISPUTES { get; set; }
        public virtual DbSet<CLEARANCE_LOG> CLEARANCE_LOG { get; set; }
        public virtual DbSet<CLEARANCE_STATUS> CLEARANCE_STATUS { get; set; }
        public virtual DbSet<CLEARANCE_UNITS> CLEARANCE_UNITS { get; set; }
        public virtual DbSet<COMPLAIN_LOG> COMPLAIN_LOG { get; set; }
        public virtual DbSet<CONFRENCE> CONFRENCE { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<COURSE> COURSE { get; set; }
        public virtual DbSet<COURSE_ALLOCATION> COURSE_ALLOCATION { get; set; }
        public virtual DbSet<COURSE_EVALUATION_ANSWER> COURSE_EVALUATION_ANSWER { get; set; }
        public virtual DbSet<COURSE_EVALUATION_QUESTION> COURSE_EVALUATION_QUESTION { get; set; }
        public virtual DbSet<COURSE_MODE> COURSE_MODE { get; set; }
        public virtual DbSet<COURSE_REGISTRATION_STATUS> COURSE_REGISTRATION_STATUS { get; set; }
        public virtual DbSet<COURSE_TEACHER> COURSE_TEACHER { get; set; }
        public virtual DbSet<COURSE_TYPE> COURSE_TYPE { get; set; }
        public virtual DbSet<COURSE_UNIT> COURSE_UNIT { get; set; }
        public virtual DbSet<CURRENT_FEE> CURRENT_FEE { get; set; }
        public virtual DbSet<CURRENT_SESSION_SEMESTER> CURRENT_SESSION_SEMESTER { get; set; }
        public virtual DbSet<DAY> DAY { get; set; }
        public virtual DbSet<DAY_ACTIVITY> DAY_ACTIVITY { get; set; }
        public virtual DbSet<DELIVERY_SERVICE> DELIVERY_SERVICE { get; set; }
        public virtual DbSet<DELIVERY_SERVICE_ZONE> DELIVERY_SERVICE_ZONE { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<DEPARTMENT_CAPACITY> DEPARTMENT_CAPACITY { get; set; }
        public virtual DbSet<DEPARTMENT_HEAD> DEPARTMENT_HEAD { get; set; }
        public virtual DbSet<DEPARTMENT_OPTION> DEPARTMENT_OPTION { get; set; }
        public virtual DbSet<DISPLAY_MESSAGE> DISPLAY_MESSAGE { get; set; }
        public virtual DbSet<EDUCATIONAL_QUALIFICATION> EDUCATIONAL_QUALIFICATION { get; set; }
        public virtual DbSet<FACULTY> FACULTY { get; set; }
        public virtual DbSet<FACULTY_OFFICER> FACULTY_OFFICER { get; set; }
        public virtual DbSet<FEE> FEE { get; set; }
        public virtual DbSet<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual DbSet<FEE_DETAIL_AUDIT> FEE_DETAIL_AUDIT { get; set; }
        public virtual DbSet<FEE_TYPE> FEE_TYPE { get; set; }
        public virtual DbSet<GENERAL_AUDIT> GENERAL_AUDIT { get; set; }
        public virtual DbSet<GENOTYPE> GENOTYPE { get; set; }
        public virtual DbSet<GEO_ZONE> GEO_ZONE { get; set; }
        public virtual DbSet<GRADE_LEVEL> GRADE_LEVEL { get; set; }
        public virtual DbSet<HOSTEL> HOSTEL { get; set; }
        public virtual DbSet<HOSTEL_ALLOCATION> HOSTEL_ALLOCATION { get; set; }
        public virtual DbSet<HOSTEL_ALLOCATION_COUNT> HOSTEL_ALLOCATION_COUNT { get; set; }
        public virtual DbSet<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual DbSet<HOSTEL_AMOUNT> HOSTEL_AMOUNT { get; set; }
        public virtual DbSet<HOSTEL_BLACKLIST> HOSTEL_BLACKLIST { get; set; }
        public virtual DbSet<HOSTEL_FEE> HOSTEL_FEE { get; set; }
        public virtual DbSet<HOSTEL_REQUEST> HOSTEL_REQUEST { get; set; }
        public virtual DbSet<HOSTEL_REQUEST_COUNT> HOSTEL_REQUEST_COUNT { get; set; }
        public virtual DbSet<HOSTEL_ROOM> HOSTEL_ROOM { get; set; }
        public virtual DbSet<HOSTEL_ROOM_CORNER> HOSTEL_ROOM_CORNER { get; set; }
        public virtual DbSet<HOSTEL_SERIES> HOSTEL_SERIES { get; set; }
        public virtual DbSet<HOSTEL_TYPE> HOSTEL_TYPE { get; set; }
        public virtual DbSet<ILLNESS> ILLNESS { get; set; }
        public virtual DbSet<INSTITUTION> INSTITUTION { get; set; }
        public virtual DbSet<INSTITUTION_CHOICE> INSTITUTION_CHOICE { get; set; }
        public virtual DbSet<INSTITUTION_TYPE> INSTITUTION_TYPE { get; set; }
        public virtual DbSet<IT_DURATION> IT_DURATION { get; set; }
        public virtual DbSet<JOB_ROLE> JOB_ROLE { get; set; }
        public virtual DbSet<LEVEL> LEVEL { get; set; }
        public virtual DbSet<LEVEL_CLASS_ROOM> LEVEL_CLASS_ROOM { get; set; }
        public virtual DbSet<LOCAL_GOVERNMENT> LOCAL_GOVERNMENT { get; set; }
        public virtual DbSet<MARITAL_STATUS> MARITAL_STATUS { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MENU_GROUP> MENU_GROUP { get; set; }
        public virtual DbSet<MENU_IN_ROLE> MENU_IN_ROLE { get; set; }
        public virtual DbSet<MODE_OF_ENTRY> MODE_OF_ENTRY { get; set; }
        public virtual DbSet<MODE_OF_FINANCE> MODE_OF_FINANCE { get; set; }
        public virtual DbSet<MODE_OF_STUDY> MODE_OF_STUDY { get; set; }
        public virtual DbSet<NATIONALITY> NATIONALITY { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
        public virtual DbSet<NEXT_OF_KIN> NEXT_OF_KIN { get; set; }
        public virtual DbSet<O_LEVEL_EXAM_SITTING> O_LEVEL_EXAM_SITTING { get; set; }
        public virtual DbSet<O_LEVEL_GRADE> O_LEVEL_GRADE { get; set; }
        public virtual DbSet<O_LEVEL_SUBJECT> O_LEVEL_SUBJECT { get; set; }
        public virtual DbSet<O_LEVEL_TYPE> O_LEVEL_TYPE { get; set; }
        public virtual DbSet<OCCUPATION> OCCUPATION { get; set; }
        public virtual DbSet<OFFENCE> OFFENCE { get; set; }
        public virtual DbSet<OFFENCE_DEGREE> OFFENCE_DEGREE { get; set; }
        public virtual DbSet<OFFENCE_PUNISHMENT> OFFENCE_PUNISHMENT { get; set; }
        public virtual DbSet<ONLINE_PAYMENT> ONLINE_PAYMENT { get; set; }
        public virtual DbSet<PAYMENT> PAYMENT { get; set; }
        public virtual DbSet<PAYMENT_CHANNEL> PAYMENT_CHANNEL { get; set; }
        public virtual DbSet<PAYMENT_ETRANZACT> PAYMENT_ETRANZACT { get; set; }
        public virtual DbSet<PAYMENT_ETRANZACT_TYPE> PAYMENT_ETRANZACT_TYPE { get; set; }
        public virtual DbSet<PAYMENT_MODE> PAYMENT_MODE { get; set; }
        public virtual DbSet<PAYMENT_PAYSTACK> PAYMENT_PAYSTACK { get; set; }
        public virtual DbSet<PAYMENT_SCHOLARSHIP> PAYMENT_SCHOLARSHIP { get; set; }
        public virtual DbSet<PAYMENT_TERMINAL> PAYMENT_TERMINAL { get; set; }
        public virtual DbSet<PAYMENT_TYPE> PAYMENT_TYPE { get; set; }
        public virtual DbSet<PAYMENT_VERIFICATION> PAYMENT_VERIFICATION { get; set; }
        public virtual DbSet<PERIOD> PERIOD { get; set; }
        public virtual DbSet<PERSON> PERSON { get; set; }
        public virtual DbSet<PERSON_AUDIT> PERSON_AUDIT { get; set; }
        public virtual DbSet<PERSON_LOGIN> PERSON_LOGIN { get; set; }
        public virtual DbSet<PERSON_TYPE> PERSON_TYPE { get; set; }
        public virtual DbSet<POST_UTME_RESULT> POST_UTME_RESULT { get; set; }
        public virtual DbSet<PROGRAMME> PROGRAMME { get; set; }
        public virtual DbSet<PROGRAMME_DEPARTMENT> PROGRAMME_DEPARTMENT { get; set; }
        public virtual DbSet<PUNISHMENT> PUNISHMENT { get; set; }
        public virtual DbSet<PUNISHMENT_STATUS> PUNISHMENT_STATUS { get; set; }
        public virtual DbSet<PUTME_RESULT> PUTME_RESULT { get; set; }
        public virtual DbSet<PUTME_RESULT_AUDIT> PUTME_RESULT_AUDIT { get; set; }
        public virtual DbSet<RANKING_DATA> RANKING_DATA { get; set; }
        public virtual DbSet<RATING> RATING { get; set; }
        public virtual DbSet<RELATIONSHIP> RELATIONSHIP { get; set; }
        public virtual DbSet<RELIGION> RELIGION { get; set; }
        public virtual DbSet<REMITA_PAYMENT> REMITA_PAYMENT { get; set; }
        public virtual DbSet<REMITA_PAYMENT_SETTINGS> REMITA_PAYMENT_SETTINGS { get; set; }
        public virtual DbSet<REMITA_SPLIT_DETAILS> REMITA_SPLIT_DETAILS { get; set; }
        public virtual DbSet<REPORT_CARD> REPORT_CARD { get; set; }
        public virtual DbSet<REPORT_CARD_COMMENT> REPORT_CARD_COMMENT { get; set; }
        public virtual DbSet<RESULT_GRADE> RESULT_GRADE { get; set; }
        public virtual DbSet<RIGHT> RIGHT { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<ROLE_RIGHT> ROLE_RIGHT { get; set; }
        public virtual DbSet<SCORE_GRADE> SCORE_GRADE { get; set; }
        public virtual DbSet<SCRATCH_CARD> SCRATCH_CARD { get; set; }
        public virtual DbSet<SCRATCH_CARD_BATCH> SCRATCH_CARD_BATCH { get; set; }
        public virtual DbSet<SCRATCH_CARD_TYPE> SCRATCH_CARD_TYPE { get; set; }
        public virtual DbSet<SECURITY_QUESTION> SECURITY_QUESTION { get; set; }
        public virtual DbSet<SEMESTER> SEMESTER { get; set; }
        public virtual DbSet<SESSION> SESSION { get; set; }
        public virtual DbSet<SESSION_SEMESTER> SESSION_SEMESTER { get; set; }
        public virtual DbSet<SEX> SEX { get; set; }
        public virtual DbSet<SHORT_FALL> SHORT_FALL { get; set; }
        public virtual DbSet<STAFF> STAFF { get; set; }
        public virtual DbSet<STAFF_DEPARTMENT> STAFF_DEPARTMENT { get; set; }
        public virtual DbSet<STAFF_JOB_ROLE> STAFF_JOB_ROLE { get; set; }
        public virtual DbSet<STAFF_TYPE> STAFF_TYPE { get; set; }
        public virtual DbSet<STATE> STATE { get; set; }
        public virtual DbSet<STATE_GEO_ZONE> STATE_GEO_ZONE { get; set; }
        public virtual DbSet<STUDENT_ACADEMIC_INFORMATION> STUDENT_ACADEMIC_INFORMATION { get; set; }
        public virtual DbSet<STUDENT_ASSESSMENT_CRITERIA> STUDENT_ASSESSMENT_CRITERIA { get; set; }
        public virtual DbSet<STUDENT_CATEGORY> STUDENT_CATEGORY { get; set; }
        public virtual DbSet<STUDENT_COURSE_REGISTRATION> STUDENT_COURSE_REGISTRATION { get; set; }
        public virtual DbSet<STUDENT_COURSE_REGISTRATION_DETAIL> STUDENT_COURSE_REGISTRATION_DETAIL { get; set; }
        public virtual DbSet<STUDENT_COURSE_REGISTRATION_DETAIL_AUDIT> STUDENT_COURSE_REGISTRATION_DETAIL_AUDIT { get; set; }
        public virtual DbSet<STUDENT_DEFERMENT_LOG> STUDENT_DEFERMENT_LOG { get; set; }
        public virtual DbSet<STUDENT_EMPLOYMENT_INFORMATION> STUDENT_EMPLOYMENT_INFORMATION { get; set; }
        public virtual DbSet<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT> STUDENT_EXAM_RAW_SCORE_SHEET_RESULT { get; set; }
        public virtual DbSet<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED> STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED { get; set; }
        public virtual DbSet<STUDENT_EXTRA_YEAR_SESSION> STUDENT_EXTRA_YEAR_SESSION { get; set; }
        public virtual DbSet<STUDENT_FINANCE_INFORMATION> STUDENT_FINANCE_INFORMATION { get; set; }
        public virtual DbSet<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
        public virtual DbSet<STUDENT_LEVEL_HISTORY> STUDENT_LEVEL_HISTORY { get; set; }
        public virtual DbSet<STUDENT_MATRIC_NUMBER_ASSIGNMENT> STUDENT_MATRIC_NUMBER_ASSIGNMENT { get; set; }
        public virtual DbSet<STUDENT_ND_RESULT> STUDENT_ND_RESULT { get; set; }
        public virtual DbSet<STUDENT_PAYMENT> STUDENT_PAYMENT { get; set; }
        public virtual DbSet<STUDENT_RESULT> STUDENT_RESULT { get; set; }
        public virtual DbSet<STUDENT_RESULT_DETAIL> STUDENT_RESULT_DETAIL { get; set; }
        public virtual DbSet<STUDENT_RESULT_TYPE> STUDENT_RESULT_TYPE { get; set; }
        public virtual DbSet<STUDENT_SCORE> STUDENT_SCORE { get; set; }
        public virtual DbSet<STUDENT_SEMESTER> STUDENT_SEMESTER { get; set; }
        public virtual DbSet<STUDENT_SPONSOR> STUDENT_SPONSOR { get; set; }
        public virtual DbSet<STUDENT_STATUS> STUDENT_STATUS { get; set; }
        public virtual DbSet<STUDENT_TYPE> STUDENT_TYPE { get; set; }
        public virtual DbSet<STUDENT_UPDATE_AUDIT> STUDENT_UPDATE_AUDIT { get; set; }
        public virtual DbSet<TITLE> TITLE { get; set; }
        public virtual DbSet<TRANSCRIPT_CLEARANCE_STATUS> TRANSCRIPT_CLEARANCE_STATUS { get; set; }
        public virtual DbSet<TRANSCRIPT_STATUS> TRANSCRIPT_STATUS { get; set; }
        public virtual DbSet<VENUE_DESIGNATION> VENUE_DESIGNATION { get; set; }
        public virtual DbSet<MIGRA> MIGRA { get; set; }
        public virtual DbSet<PAID> PAID { get; set; }
        public virtual DbSet<TEMPEVALUATIONTABLE> TEMPEVALUATIONTABLE { get; set; }
        public virtual DbSet<tmp_CourseReg> tmp_CourseReg { get; set; }
        public virtual DbSet<WRONG_CARRYOVER> WRONG_CARRYOVER { get; set; }
        public virtual DbSet<ACCPTANCE__REPORT> ACCPTANCE__REPORT { get; set; }
        public virtual DbSet<VW_ACCEPTANCE_REPORT> VW_ACCEPTANCE_REPORT { get; set; }
        public virtual DbSet<VW_ADMISSION_AUDIT> VW_ADMISSION_AUDIT { get; set; }
        public virtual DbSet<VW_ADMISSION_LIST> VW_ADMISSION_LIST { get; set; }
        public virtual DbSet<VW_ADMISSION_LIST_ALL> VW_ADMISSION_LIST_ALL { get; set; }
        public virtual DbSet<VW_ALL_PAYMENT_REPORT_NEW_STUDENTS> VW_ALL_PAYMENT_REPORT_NEW_STUDENTS { get; set; }
        public virtual DbSet<VW_ALL_PAYMENT_REPORT_RETURNING_STUDENT> VW_ALL_PAYMENT_REPORT_RETURNING_STUDENT { get; set; }
        public virtual DbSet<VW_APPLICANT_PAYMENT> VW_APPLICANT_PAYMENT { get; set; }
        public virtual DbSet<VW_APPLICANT_RESULT> VW_APPLICANT_RESULT { get; set; }
        public virtual DbSet<VW_APPLICATION_EXAM_NUMBER> VW_APPLICATION_EXAM_NUMBER { get; set; }
        public virtual DbSet<VW_APPLICATION_FORM_SUMMARY> VW_APPLICATION_FORM_SUMMARY { get; set; }
        public virtual DbSet<VW_APPLIED_COURSE_AUDIT> VW_APPLIED_COURSE_AUDIT { get; set; }
        public virtual DbSet<VW_ASSIGNED_MATRIC_NUMBER> VW_ASSIGNED_MATRIC_NUMBER { get; set; }
        public virtual DbSet<VW_CERTIFICATE_VERFICATION_REMITA> VW_CERTIFICATE_VERFICATION_REMITA { get; set; }
        public virtual DbSet<VW_CONFIRMED_PAYMENTS> VW_CONFIRMED_PAYMENTS { get; set; }
        public virtual DbSet<VW_COURSE_EVALUATION_SCORES> VW_COURSE_EVALUATION_SCORES { get; set; }
        public virtual DbSet<VW_COURSE_REGISTRATION_SUMMARY> VW_COURSE_REGISTRATION_SUMMARY { get; set; }
        public virtual DbSet<VW_DEBTORS_NEW_STUDENT> VW_DEBTORS_NEW_STUDENT { get; set; }
        public virtual DbSet<VW_DEBTORS_OLD_STUDENT> VW_DEBTORS_OLD_STUDENT { get; set; }
        public virtual DbSet<VW_DEPARTMENT_OPTION> VW_DEPARTMENT_OPTION { get; set; }
        public virtual DbSet<VW_DUPLICATE_APPLICATION_NUMBER> VW_DUPLICATE_APPLICATION_NUMBER { get; set; }
        public virtual DbSet<VW_GENERAL_AUDIT> VW_GENERAL_AUDIT { get; set; }
        public virtual DbSet<VW_HND_APPLICANTS> VW_HND_APPLICANTS { get; set; }
        public virtual DbSet<VW_HOSTEL_ALLOCATION_COUNT> VW_HOSTEL_ALLOCATION_COUNT { get; set; }
        public virtual DbSet<VW_NEW_STUDENT> VW_NEW_STUDENT { get; set; }
        public virtual DbSet<VW_OLD_STUDENT> VW_OLD_STUDENT { get; set; }
        public virtual DbSet<VW_PAID_FEES_NOT_REGISTERED> VW_PAID_FEES_NOT_REGISTERED { get; set; }
        public virtual DbSet<VW_PAYMENT> VW_PAYMENT { get; set; }
        public virtual DbSet<VW_PAYMENT_ETRANZACT> VW_PAYMENT_ETRANZACT { get; set; }
        public virtual DbSet<VW_PAYMENT_NEW_STUDENT_COMPREHENSIVE> VW_PAYMENT_NEW_STUDENT_COMPREHENSIVE { get; set; }
        public virtual DbSet<VW_PAYMENT_NEW_STUDENT_FIRST> VW_PAYMENT_NEW_STUDENT_FIRST { get; set; }
        public virtual DbSet<VW_PAYMENT_NEW_STUDENT_FULL> VW_PAYMENT_NEW_STUDENT_FULL { get; set; }
        public virtual DbSet<VW_PAYMENT_OLD_STUDENT_COMPREHENSIVE> VW_PAYMENT_OLD_STUDENT_COMPREHENSIVE { get; set; }
        public virtual DbSet<VW_PAYMENT_OLD_STUDENT_FIRST> VW_PAYMENT_OLD_STUDENT_FIRST { get; set; }
        public virtual DbSet<VW_PAYMENT_OLD_STUDENT_FULL> VW_PAYMENT_OLD_STUDENT_FULL { get; set; }
        public virtual DbSet<VW_PAYMENT_SUMMARY> VW_PAYMENT_SUMMARY { get; set; }
        public virtual DbSet<VW_PAYMENT_SUMMARY_ETRANZACT> VW_PAYMENT_SUMMARY_ETRANZACT { get; set; }
        public virtual DbSet<VW_PAYMENT_SUMMARY_REMITA> VW_PAYMENT_SUMMARY_REMITA { get; set; }
        public virtual DbSet<VW_PERSON_APPLICATION> VW_PERSON_APPLICATION { get; set; }
        public virtual DbSet<VW_POST_JAMP_APPLICATION> VW_POST_JAMP_APPLICATION { get; set; }
        public virtual DbSet<VW_POST_JAMP_APPLICATION_ND_REGULAR> VW_POST_JAMP_APPLICATION_ND_REGULAR { get; set; }
        public virtual DbSet<VW_PROGRAMME_DEPARTMENT> VW_PROGRAMME_DEPARTMENT { get; set; }
        public virtual DbSet<VW_PROSPECTIVE_STUDENT> VW_PROSPECTIVE_STUDENT { get; set; }
        public virtual DbSet<VW_PUTME_RESULT_DETAILS> VW_PUTME_RESULT_DETAILS { get; set; }
        public virtual DbSet<VW_REGISTERED_COURSES> VW_REGISTERED_COURSES { get; set; }
        public virtual DbSet<VW_REMITA_PAYMENT> VW_REMITA_PAYMENT { get; set; }
        public virtual DbSet<VW_RESULT_UPDATES> VW_RESULT_UPDATES { get; set; }
        public virtual DbSet<VW_STUDENT_DETAILS> VW_STUDENT_DETAILS { get; set; }
        public virtual DbSet<VW_STUDENT_PAYMENT> VW_STUDENT_PAYMENT { get; set; }
        public virtual DbSet<VW_STUDENT_REGISTERED_COURSE_CARRYOVER> VW_STUDENT_REGISTERED_COURSE_CARRYOVER { get; set; }
        public virtual DbSet<VW_STUDENT_REGISTERED_COURSES> VW_STUDENT_REGISTERED_COURSES { get; set; }
        public virtual DbSet<VW_STUDENT_REGISTERED_COURSES_REPORT> VW_STUDENT_REGISTERED_COURSES_REPORT { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT> VW_STUDENT_RESULT { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_2> VW_STUDENT_RESULT_2 { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_MASTER_LIST> VW_STUDENT_RESULT_MASTER_LIST { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_OLD_GRADING_SYSTEM> VW_STUDENT_RESULT_OLD_GRADING_SYSTEM { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_RAW_SCORE_SHEET> VW_STUDENT_RESULT_RAW_SCORE_SHEET { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_RAW_SCORE_SHEET_UNREGISTERED> VW_STUDENT_RESULT_RAW_SCORE_SHEET_UNREGISTERED { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_WITH_OPTIONS> VW_STUDENT_RESULT_WITH_OPTIONS { get; set; }
        public virtual DbSet<VW_STUDENT_WITHOUT_RESULT> VW_STUDENT_WITHOUT_RESULT { get; set; }
        public virtual DbSet<VW_STUDENTS_PAID_BUT_UNREGISTERED> VW_STUDENTS_PAID_BUT_UNREGISTERED { get; set; }
        public virtual DbSet<VW_STUDENTS_WITH_NO_SCHOOL_FEES> VW_STUDENTS_WITH_NO_SCHOOL_FEES { get; set; }
        public virtual DbSet<VW_TRANSCRIPT_REQUEST> VW_TRANSCRIPT_REQUEST { get; set; }
        public virtual DbSet<VW_TRANSCRIPT_REQUEST_REMITA> VW_TRANSCRIPT_REQUEST_REMITA { get; set; }
        public virtual DbSet<VW_TRANSCRIPT_VERIFICATION_REMITA> VW_TRANSCRIPT_VERIFICATION_REMITA { get; set; }
        public virtual DbSet<VW_TRANSCRIPT_VERIFICATION_REMITA2> VW_TRANSCRIPT_VERIFICATION_REMITA2 { get; set; }
        public virtual DbSet<VW_UPLOADED_COURSES> VW_UPLOADED_COURSES { get; set; }
        public virtual DbSet<VW_VACANT_BEDSPACES> VW_VACANT_BEDSPACES { get; set; }
        public virtual DbSet<VW_VERIFICATION_REPORT> VW_VERIFICATION_REPORT { get; set; }
        public virtual DbSet<STUDENT_RESULT_STATUS> STUDENT_RESULT_STATUS { get; set; }
        public virtual DbSet<VW_STUDENT_RESULT_SUMMARY> VW_STUDENT_RESULT_SUMMARY { get; set; }
        public virtual DbSet<VW_VERIFIED_CERTIFICATE_VERIFICATION_PAYMENT> VW_VERIFIED_CERTIFICATE_VERIFICATION_PAYMENT { get; set; }
        public virtual DbSet<VW_VERIFIED_TRANSCRIPT_PAYMENT> VW_VERIFIED_TRANSCRIPT_PAYMENT { get; set; }
        public virtual DbSet<VW_VERIFIED_TRANSCRIPT_VERIFICATION_PAYMENT> VW_VERIFIED_TRANSCRIPT_VERIFICATION_PAYMENT { get; set; }
        public virtual DbSet<E_COURSE_CONTENT_DOWNLOAD> E_COURSE_CONTENT_DOWNLOAD { get; set; }
        public virtual DbSet<VW_ELEARNING_COURSE_CONTENT> VW_ELEARNING_COURSE_CONTENT { get; set; }
        public virtual DbSet<E_ASSIGNMENT_SUBMISSION> E_ASSIGNMENT_SUBMISSION { get; set; }
        public virtual DbSet<E_CHAT_RESPONPSE> E_CHAT_RESPONPSE { get; set; }
        public virtual DbSet<E_CONTENT_TYPE> E_CONTENT_TYPE { get; set; }
        public virtual DbSet<E_CHAT_TOPIC> E_CHAT_TOPIC { get; set; }
        public virtual DbSet<E_COURSE_CONTENT> E_COURSE_CONTENT { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<E_ASSIGNMENT> E_ASSIGNMENT { get; set; }
        public virtual DbSet<VW_APPLICATION_FORM_COUNT> VW_APPLICATION_FORM_COUNT { get; set; }
        public virtual DbSet<PRINCIPAL_OFFICERS> PRINCIPAL_OFFICERS { get; set; }
        public virtual DbSet<APPLICANT_PREVIOUS_EDUCATION> APPLICANT_PREVIOUS_EDUCATION { get; set; }
        public virtual DbSet<VW_APPLICANT_UPLOAD> VW_APPLICANT_UPLOAD { get; set; }
        public virtual DbSet<VW_APPLICANT_DETAILS_HND> VW_APPLICANT_DETAILS_HND { get; set; }
        public virtual DbSet<FEE_SETUP> FEE_SETUP { get; set; }
        public virtual DbSet<FEE_SETUP_AUDIT> FEE_SETUP_AUDIT { get; set; }
        public virtual DbSet<FEESETUP_FEE> FEESETUP_FEE { get; set; }
        public virtual DbSet<VW_PAYMENT_VERIFICATION_NEW_STUDENT> VW_PAYMENT_VERIFICATION_NEW_STUDENT { get; set; }
        public virtual DbSet<VW_PAYMENT_VERIFICATION_OLD_STUDENT> VW_PAYMENT_VERIFICATION_OLD_STUDENT { get; set; }
        public virtual DbSet<DRIVING_EXPERIENCE> DRIVING_EXPERIENCE { get; set; }
        public virtual DbSet<LICENSE_TYPE> LICENSE_TYPE { get; set; }
        public virtual DbSet<APPLICANT_APPLICATION_APPROVAL> APPLICANT_APPLICATION_APPROVAL { get; set; }
        public virtual DbSet<VW_APPLICANT_APPLICATION_APPROVAL_SUMMARY> VW_APPLICANT_APPLICATION_APPROVAL_SUMMARY { get; set; }
        public virtual DbSet<LIVE_LECTURE_ATTENDANCE> LIVE_LECTURE_ATTENDANCE { get; set; }
        public virtual DbSet<LIVE_LECTURES> LIVE_LECTURES { get; set; }
        public virtual DbSet<FEEDBACK_STORE> FEEDBACK_STORE { get; set; }
        public virtual DbSet<JAMB_O_LEVEL> JAMB_O_LEVEL { get; set; }
        public virtual DbSet<JAMB_O_LEVEL_DETAIL> JAMB_O_LEVEL_DETAIL { get; set; }
        public virtual DbSet<JAMB_RECORD> JAMB_RECORD { get; set; }
        public virtual DbSet<VW_ACCEPTANCE_VERIFICATION> VW_ACCEPTANCE_VERIFICATION { get; set; }
        public virtual DbSet<VW_SCHOOL_FEES_VERIFICATION> VW_SCHOOL_FEES_VERIFICATION { get; set; }
        public virtual DbSet<VW_PAYMENT_CONFIRMATION> VW_PAYMENT_CONFIRMATION { get; set; }
        public virtual DbSet<VW_SCHOOL_FEES_PAYMENT> VW_SCHOOL_FEES_PAYMENT { get; set; }
        public virtual DbSet<VW_PAYMENT_CONFIRMATION_NEW_STUDENTS> VW_PAYMENT_CONFIRMATION_NEW_STUDENTS { get; set; }
        public virtual DbSet<FEE_IN_PAYMENT> FEE_IN_PAYMENT { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<REGENERATED_CLEARED_INVOICE> REGENERATED_CLEARED_INVOICE { get; set; }
        public virtual DbSet<VW_ADMISSION_LIST_SUMMARY> VW_ADMISSION_LIST_SUMMARY { get; set; }
        public virtual DbSet<TRANSCRIPT_REQUEST> TRANSCRIPT_REQUEST { get; set; }
    
        public virtual int STP_DELETE_APPLICATION_FORM(Nullable<long> paramApplication_Form_Id)
        {
            var paramApplication_Form_IdParameter = paramApplication_Form_Id.HasValue ?
                new ObjectParameter("paramApplication_Form_Id", paramApplication_Form_Id) :
                new ObjectParameter("paramApplication_Form_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DELETE_APPLICATION_FORM", paramApplication_Form_IdParameter);
        }
    
        public virtual ObjectResult<STP_INSERT_APPLICATION_FORM_Result> STP_INSERT_APPLICATION_FORM(Nullable<long> paramSerial_Number, string paramApplication_Form_Number, Nullable<int> paramApplication_Exam_Serial_Number, string paramApplication_Exam_Number, Nullable<int> paramApplication_Form_Setting_Id, Nullable<int> paramApplication_Programme_Fee_Id, Nullable<long> paramPayment_Id, Nullable<long> paramPerson_Id, Nullable<System.DateTime> paramDate_Submitted, Nullable<bool> paramRelease, Nullable<bool> paramRejected, string paramReject_Reason, string paramRemarks)
        {
            var paramSerial_NumberParameter = paramSerial_Number.HasValue ?
                new ObjectParameter("paramSerial_Number", paramSerial_Number) :
                new ObjectParameter("paramSerial_Number", typeof(long));
    
            var paramApplication_Form_NumberParameter = paramApplication_Form_Number != null ?
                new ObjectParameter("paramApplication_Form_Number", paramApplication_Form_Number) :
                new ObjectParameter("paramApplication_Form_Number", typeof(string));
    
            var paramApplication_Exam_Serial_NumberParameter = paramApplication_Exam_Serial_Number.HasValue ?
                new ObjectParameter("paramApplication_Exam_Serial_Number", paramApplication_Exam_Serial_Number) :
                new ObjectParameter("paramApplication_Exam_Serial_Number", typeof(int));
    
            var paramApplication_Exam_NumberParameter = paramApplication_Exam_Number != null ?
                new ObjectParameter("paramApplication_Exam_Number", paramApplication_Exam_Number) :
                new ObjectParameter("paramApplication_Exam_Number", typeof(string));
    
            var paramApplication_Form_Setting_IdParameter = paramApplication_Form_Setting_Id.HasValue ?
                new ObjectParameter("paramApplication_Form_Setting_Id", paramApplication_Form_Setting_Id) :
                new ObjectParameter("paramApplication_Form_Setting_Id", typeof(int));
    
            var paramApplication_Programme_Fee_IdParameter = paramApplication_Programme_Fee_Id.HasValue ?
                new ObjectParameter("paramApplication_Programme_Fee_Id", paramApplication_Programme_Fee_Id) :
                new ObjectParameter("paramApplication_Programme_Fee_Id", typeof(int));
    
            var paramPayment_IdParameter = paramPayment_Id.HasValue ?
                new ObjectParameter("paramPayment_Id", paramPayment_Id) :
                new ObjectParameter("paramPayment_Id", typeof(long));
    
            var paramPerson_IdParameter = paramPerson_Id.HasValue ?
                new ObjectParameter("paramPerson_Id", paramPerson_Id) :
                new ObjectParameter("paramPerson_Id", typeof(long));
    
            var paramDate_SubmittedParameter = paramDate_Submitted.HasValue ?
                new ObjectParameter("paramDate_Submitted", paramDate_Submitted) :
                new ObjectParameter("paramDate_Submitted", typeof(System.DateTime));
    
            var paramReleaseParameter = paramRelease.HasValue ?
                new ObjectParameter("paramRelease", paramRelease) :
                new ObjectParameter("paramRelease", typeof(bool));
    
            var paramRejectedParameter = paramRejected.HasValue ?
                new ObjectParameter("paramRejected", paramRejected) :
                new ObjectParameter("paramRejected", typeof(bool));
    
            var paramReject_ReasonParameter = paramReject_Reason != null ?
                new ObjectParameter("paramReject_Reason", paramReject_Reason) :
                new ObjectParameter("paramReject_Reason", typeof(string));
    
            var paramRemarksParameter = paramRemarks != null ?
                new ObjectParameter("paramRemarks", paramRemarks) :
                new ObjectParameter("paramRemarks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_INSERT_APPLICATION_FORM_Result>("STP_INSERT_APPLICATION_FORM", paramSerial_NumberParameter, paramApplication_Form_NumberParameter, paramApplication_Exam_Serial_NumberParameter, paramApplication_Exam_NumberParameter, paramApplication_Form_Setting_IdParameter, paramApplication_Programme_Fee_IdParameter, paramPayment_IdParameter, paramPerson_IdParameter, paramDate_SubmittedParameter, paramReleaseParameter, paramRejectedParameter, paramReject_ReasonParameter, paramRemarksParameter);
        }
    
        public virtual ObjectResult<STP_UPDATE_APPLICATION_FORM_Result> STP_UPDATE_APPLICATION_FORM(Nullable<long> paramApplication_Form_Id, Nullable<long> paramSerial_Number, string paramApplication_Form_Number, Nullable<int> paramApplication_Exam_Serial_Number, string paramApplication_Exam_Number, Nullable<int> paramApplication_Form_Setting_Id, Nullable<int> paramApplication_Programme_Fee_Id, Nullable<long> paramPayment_Id, Nullable<long> paramPerson_Id, Nullable<System.DateTime> paramDate_Submitted, Nullable<bool> paramRelease, Nullable<bool> paramRejected, string paramReject_Reason, string paramRemarks, Nullable<bool> paramVerificationStatus, string paramVerificationComment, Nullable<long> paramVerificationOfficer)
        {
            var paramApplication_Form_IdParameter = paramApplication_Form_Id.HasValue ?
                new ObjectParameter("paramApplication_Form_Id", paramApplication_Form_Id) :
                new ObjectParameter("paramApplication_Form_Id", typeof(long));
    
            var paramSerial_NumberParameter = paramSerial_Number.HasValue ?
                new ObjectParameter("paramSerial_Number", paramSerial_Number) :
                new ObjectParameter("paramSerial_Number", typeof(long));
    
            var paramApplication_Form_NumberParameter = paramApplication_Form_Number != null ?
                new ObjectParameter("paramApplication_Form_Number", paramApplication_Form_Number) :
                new ObjectParameter("paramApplication_Form_Number", typeof(string));
    
            var paramApplication_Exam_Serial_NumberParameter = paramApplication_Exam_Serial_Number.HasValue ?
                new ObjectParameter("paramApplication_Exam_Serial_Number", paramApplication_Exam_Serial_Number) :
                new ObjectParameter("paramApplication_Exam_Serial_Number", typeof(int));
    
            var paramApplication_Exam_NumberParameter = paramApplication_Exam_Number != null ?
                new ObjectParameter("paramApplication_Exam_Number", paramApplication_Exam_Number) :
                new ObjectParameter("paramApplication_Exam_Number", typeof(string));
    
            var paramApplication_Form_Setting_IdParameter = paramApplication_Form_Setting_Id.HasValue ?
                new ObjectParameter("paramApplication_Form_Setting_Id", paramApplication_Form_Setting_Id) :
                new ObjectParameter("paramApplication_Form_Setting_Id", typeof(int));
    
            var paramApplication_Programme_Fee_IdParameter = paramApplication_Programme_Fee_Id.HasValue ?
                new ObjectParameter("paramApplication_Programme_Fee_Id", paramApplication_Programme_Fee_Id) :
                new ObjectParameter("paramApplication_Programme_Fee_Id", typeof(int));
    
            var paramPayment_IdParameter = paramPayment_Id.HasValue ?
                new ObjectParameter("paramPayment_Id", paramPayment_Id) :
                new ObjectParameter("paramPayment_Id", typeof(long));
    
            var paramPerson_IdParameter = paramPerson_Id.HasValue ?
                new ObjectParameter("paramPerson_Id", paramPerson_Id) :
                new ObjectParameter("paramPerson_Id", typeof(long));
    
            var paramDate_SubmittedParameter = paramDate_Submitted.HasValue ?
                new ObjectParameter("paramDate_Submitted", paramDate_Submitted) :
                new ObjectParameter("paramDate_Submitted", typeof(System.DateTime));
    
            var paramReleaseParameter = paramRelease.HasValue ?
                new ObjectParameter("paramRelease", paramRelease) :
                new ObjectParameter("paramRelease", typeof(bool));
    
            var paramRejectedParameter = paramRejected.HasValue ?
                new ObjectParameter("paramRejected", paramRejected) :
                new ObjectParameter("paramRejected", typeof(bool));
    
            var paramReject_ReasonParameter = paramReject_Reason != null ?
                new ObjectParameter("paramReject_Reason", paramReject_Reason) :
                new ObjectParameter("paramReject_Reason", typeof(string));
    
            var paramRemarksParameter = paramRemarks != null ?
                new ObjectParameter("paramRemarks", paramRemarks) :
                new ObjectParameter("paramRemarks", typeof(string));
    
            var paramVerificationStatusParameter = paramVerificationStatus.HasValue ?
                new ObjectParameter("paramVerificationStatus", paramVerificationStatus) :
                new ObjectParameter("paramVerificationStatus", typeof(bool));
    
            var paramVerificationCommentParameter = paramVerificationComment != null ?
                new ObjectParameter("paramVerificationComment", paramVerificationComment) :
                new ObjectParameter("paramVerificationComment", typeof(string));
    
            var paramVerificationOfficerParameter = paramVerificationOfficer.HasValue ?
                new ObjectParameter("paramVerificationOfficer", paramVerificationOfficer) :
                new ObjectParameter("paramVerificationOfficer", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_UPDATE_APPLICATION_FORM_Result>("STP_UPDATE_APPLICATION_FORM", paramApplication_Form_IdParameter, paramSerial_NumberParameter, paramApplication_Form_NumberParameter, paramApplication_Exam_Serial_NumberParameter, paramApplication_Exam_NumberParameter, paramApplication_Form_Setting_IdParameter, paramApplication_Programme_Fee_IdParameter, paramPayment_IdParameter, paramPerson_IdParameter, paramDate_SubmittedParameter, paramReleaseParameter, paramRejectedParameter, paramReject_ReasonParameter, paramRemarksParameter, paramVerificationStatusParameter, paramVerificationCommentParameter, paramVerificationOfficerParameter);
        }
    
        public virtual int STP_DELETE_STUDENT(Nullable<long> paramPerson_Id)
        {
            var paramPerson_IdParameter = paramPerson_Id.HasValue ?
                new ObjectParameter("paramPerson_Id", paramPerson_Id) :
                new ObjectParameter("paramPerson_Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STP_DELETE_STUDENT", paramPerson_IdParameter);
        }
    
        public virtual ObjectResult<STP_INSERT_STUDENT_Result> STP_INSERT_STUDENT(Nullable<long> paramPerson_Id, Nullable<long> paramApplication_Form_Id, Nullable<int> paramStudent_Type_Id, Nullable<int> paramStudent_Category_Id, Nullable<int> paramStudent_Status_Id, Nullable<long> paramStudent_Number, string paramMatric_Number, Nullable<int> paramTitle_Id, Nullable<int> paramMarital_Status_Id, Nullable<int> paramBlood_Group_Id, Nullable<int> paramGenotype_Id, string paramSchool_Contact_Address, Nullable<bool> paramActivated, string paramReason, string paramReject_category, string paramPassword_hash)
        {
            var paramPerson_IdParameter = paramPerson_Id.HasValue ?
                new ObjectParameter("paramPerson_Id", paramPerson_Id) :
                new ObjectParameter("paramPerson_Id", typeof(long));
    
            var paramApplication_Form_IdParameter = paramApplication_Form_Id.HasValue ?
                new ObjectParameter("paramApplication_Form_Id", paramApplication_Form_Id) :
                new ObjectParameter("paramApplication_Form_Id", typeof(long));
    
            var paramStudent_Type_IdParameter = paramStudent_Type_Id.HasValue ?
                new ObjectParameter("paramStudent_Type_Id", paramStudent_Type_Id) :
                new ObjectParameter("paramStudent_Type_Id", typeof(int));
    
            var paramStudent_Category_IdParameter = paramStudent_Category_Id.HasValue ?
                new ObjectParameter("paramStudent_Category_Id", paramStudent_Category_Id) :
                new ObjectParameter("paramStudent_Category_Id", typeof(int));
    
            var paramStudent_Status_IdParameter = paramStudent_Status_Id.HasValue ?
                new ObjectParameter("paramStudent_Status_Id", paramStudent_Status_Id) :
                new ObjectParameter("paramStudent_Status_Id", typeof(int));
    
            var paramStudent_NumberParameter = paramStudent_Number.HasValue ?
                new ObjectParameter("paramStudent_Number", paramStudent_Number) :
                new ObjectParameter("paramStudent_Number", typeof(long));
    
            var paramMatric_NumberParameter = paramMatric_Number != null ?
                new ObjectParameter("paramMatric_Number", paramMatric_Number) :
                new ObjectParameter("paramMatric_Number", typeof(string));
    
            var paramTitle_IdParameter = paramTitle_Id.HasValue ?
                new ObjectParameter("paramTitle_Id", paramTitle_Id) :
                new ObjectParameter("paramTitle_Id", typeof(int));
    
            var paramMarital_Status_IdParameter = paramMarital_Status_Id.HasValue ?
                new ObjectParameter("paramMarital_Status_Id", paramMarital_Status_Id) :
                new ObjectParameter("paramMarital_Status_Id", typeof(int));
    
            var paramBlood_Group_IdParameter = paramBlood_Group_Id.HasValue ?
                new ObjectParameter("paramBlood_Group_Id", paramBlood_Group_Id) :
                new ObjectParameter("paramBlood_Group_Id", typeof(int));
    
            var paramGenotype_IdParameter = paramGenotype_Id.HasValue ?
                new ObjectParameter("paramGenotype_Id", paramGenotype_Id) :
                new ObjectParameter("paramGenotype_Id", typeof(int));
    
            var paramSchool_Contact_AddressParameter = paramSchool_Contact_Address != null ?
                new ObjectParameter("paramSchool_Contact_Address", paramSchool_Contact_Address) :
                new ObjectParameter("paramSchool_Contact_Address", typeof(string));
    
            var paramActivatedParameter = paramActivated.HasValue ?
                new ObjectParameter("paramActivated", paramActivated) :
                new ObjectParameter("paramActivated", typeof(bool));
    
            var paramReasonParameter = paramReason != null ?
                new ObjectParameter("paramReason", paramReason) :
                new ObjectParameter("paramReason", typeof(string));
    
            var paramReject_categoryParameter = paramReject_category != null ?
                new ObjectParameter("paramReject_category", paramReject_category) :
                new ObjectParameter("paramReject_category", typeof(string));
    
            var paramPassword_hashParameter = paramPassword_hash != null ?
                new ObjectParameter("paramPassword_hash", paramPassword_hash) :
                new ObjectParameter("paramPassword_hash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_INSERT_STUDENT_Result>("STP_INSERT_STUDENT", paramPerson_IdParameter, paramApplication_Form_IdParameter, paramStudent_Type_IdParameter, paramStudent_Category_IdParameter, paramStudent_Status_IdParameter, paramStudent_NumberParameter, paramMatric_NumberParameter, paramTitle_IdParameter, paramMarital_Status_IdParameter, paramBlood_Group_IdParameter, paramGenotype_IdParameter, paramSchool_Contact_AddressParameter, paramActivatedParameter, paramReasonParameter, paramReject_categoryParameter, paramPassword_hashParameter);
        }
    
        public virtual ObjectResult<STP_UPDATE_STUDENT_Result> STP_UPDATE_STUDENT(Nullable<long> paramPerson_Id, Nullable<long> paramApplication_Form_Id, Nullable<int> paramStudent_Type_Id, Nullable<int> paramStudent_Category_Id, Nullable<int> paramStudent_Status_Id, Nullable<long> paramStudent_Number, string paramMatric_Number, Nullable<int> paramTitle_Id, Nullable<int> paramMarital_Status_Id, Nullable<int> paramBlood_Group_Id, Nullable<int> paramGenotype_Id, string paramSchool_Contact_Address, Nullable<bool> paramActivated, string paramReason, string paramReject_category, string paramPassword_hash)
        {
            var paramPerson_IdParameter = paramPerson_Id.HasValue ?
                new ObjectParameter("paramPerson_Id", paramPerson_Id) :
                new ObjectParameter("paramPerson_Id", typeof(long));
    
            var paramApplication_Form_IdParameter = paramApplication_Form_Id.HasValue ?
                new ObjectParameter("paramApplication_Form_Id", paramApplication_Form_Id) :
                new ObjectParameter("paramApplication_Form_Id", typeof(long));
    
            var paramStudent_Type_IdParameter = paramStudent_Type_Id.HasValue ?
                new ObjectParameter("paramStudent_Type_Id", paramStudent_Type_Id) :
                new ObjectParameter("paramStudent_Type_Id", typeof(int));
    
            var paramStudent_Category_IdParameter = paramStudent_Category_Id.HasValue ?
                new ObjectParameter("paramStudent_Category_Id", paramStudent_Category_Id) :
                new ObjectParameter("paramStudent_Category_Id", typeof(int));
    
            var paramStudent_Status_IdParameter = paramStudent_Status_Id.HasValue ?
                new ObjectParameter("paramStudent_Status_Id", paramStudent_Status_Id) :
                new ObjectParameter("paramStudent_Status_Id", typeof(int));
    
            var paramStudent_NumberParameter = paramStudent_Number.HasValue ?
                new ObjectParameter("paramStudent_Number", paramStudent_Number) :
                new ObjectParameter("paramStudent_Number", typeof(long));
    
            var paramMatric_NumberParameter = paramMatric_Number != null ?
                new ObjectParameter("paramMatric_Number", paramMatric_Number) :
                new ObjectParameter("paramMatric_Number", typeof(string));
    
            var paramTitle_IdParameter = paramTitle_Id.HasValue ?
                new ObjectParameter("paramTitle_Id", paramTitle_Id) :
                new ObjectParameter("paramTitle_Id", typeof(int));
    
            var paramMarital_Status_IdParameter = paramMarital_Status_Id.HasValue ?
                new ObjectParameter("paramMarital_Status_Id", paramMarital_Status_Id) :
                new ObjectParameter("paramMarital_Status_Id", typeof(int));
    
            var paramBlood_Group_IdParameter = paramBlood_Group_Id.HasValue ?
                new ObjectParameter("paramBlood_Group_Id", paramBlood_Group_Id) :
                new ObjectParameter("paramBlood_Group_Id", typeof(int));
    
            var paramGenotype_IdParameter = paramGenotype_Id.HasValue ?
                new ObjectParameter("paramGenotype_Id", paramGenotype_Id) :
                new ObjectParameter("paramGenotype_Id", typeof(int));
    
            var paramSchool_Contact_AddressParameter = paramSchool_Contact_Address != null ?
                new ObjectParameter("paramSchool_Contact_Address", paramSchool_Contact_Address) :
                new ObjectParameter("paramSchool_Contact_Address", typeof(string));
    
            var paramActivatedParameter = paramActivated.HasValue ?
                new ObjectParameter("paramActivated", paramActivated) :
                new ObjectParameter("paramActivated", typeof(bool));
    
            var paramReasonParameter = paramReason != null ?
                new ObjectParameter("paramReason", paramReason) :
                new ObjectParameter("paramReason", typeof(string));
    
            var paramReject_categoryParameter = paramReject_category != null ?
                new ObjectParameter("paramReject_category", paramReject_category) :
                new ObjectParameter("paramReject_category", typeof(string));
    
            var paramPassword_hashParameter = paramPassword_hash != null ?
                new ObjectParameter("paramPassword_hash", paramPassword_hash) :
                new ObjectParameter("paramPassword_hash", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STP_UPDATE_STUDENT_Result>("STP_UPDATE_STUDENT", paramPerson_IdParameter, paramApplication_Form_IdParameter, paramStudent_Type_IdParameter, paramStudent_Category_IdParameter, paramStudent_Status_IdParameter, paramStudent_NumberParameter, paramMatric_NumberParameter, paramTitle_IdParameter, paramMarital_Status_IdParameter, paramBlood_Group_IdParameter, paramGenotype_IdParameter, paramSchool_Contact_AddressParameter, paramActivatedParameter, paramReasonParameter, paramReject_categoryParameter, paramPassword_hashParameter);
        }
    }
}
