//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMIC_STANDING
    {
        public int Academic_Standing_Id { get; set; }
        public string Academic_Standing_Abbreviation { get; set; }
        public string Academic_Standing_Name { get; set; }
    }
}
