//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_CRITERIA_FOR_O_LEVEL_TYPE
    {
        public int Admission_Criteria_For_O_Level_Type_Id { get; set; }
        public int Admission_Criteria_Id { get; set; }
        public int O_Level_Type_Id { get; set; }
    
        public virtual ADMISSION_CRITERIA ADMISSION_CRITERIA { get; set; }
        public virtual O_LEVEL_TYPE O_LEVEL_TYPE { get; set; }
    }
}
