//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_LIST_AUDIT
    {
        public long Admission_List_Audit_Id { get; set; }
        public long Admission_List_Id { get; set; }
        public long Application_Form_Id { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public long User_Id { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public System.DateTime Time { get; set; }
        public string Client { get; set; }
    
        public virtual ADMISSION_LIST ADMISSION_LIST { get; set; }
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DEPARTMENT_OPTION DEPARTMENT_OPTION { get; set; }
        public virtual USER USER { get; set; }
    }
}
