//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_LIST
    {
        public ADMISSION_LIST()
        {
            this.ADMISSION_LIST_AUDIT = new HashSet<ADMISSION_LIST_AUDIT>();
        }
    
        public long Admission_List_Id { get; set; }
        public long Application_Form_Id { get; set; }
        public int Admission_List_Batch_Id { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<int> Session_Id { get; set; }
    
        public virtual ADMISSION_LIST_BATCH ADMISSION_LIST_BATCH { get; set; }
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual ICollection<ADMISSION_LIST_AUDIT> ADMISSION_LIST_AUDIT { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DEPARTMENT_OPTION DEPARTMENT_OPTION { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
