//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMISSION_CRITERIA
    {
        public ADMISSION_CRITERIA()
        {
            this.ADMISSION_CRITERIA_FOR_O_LEVEL_TYPE = new HashSet<ADMISSION_CRITERIA_FOR_O_LEVEL_TYPE>();
            this.ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT = new HashSet<ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT>();
        }
    
        public int Admission_Criteria_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Minimum_Required_Number_Of_Subject { get; set; }
        public System.DateTime Date_Entered { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<ADMISSION_CRITERIA_FOR_O_LEVEL_TYPE> ADMISSION_CRITERIA_FOR_O_LEVEL_TYPE { get; set; }
        public virtual ICollection<ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT> ADMISSION_CRITERIA_FOR_O_LEVEL_SUBJECT { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
    }
}
