//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_STATUS
    {
        public APPLICANT_STATUS()
        {
            this.APPLICANT = new HashSet<APPLICANT>();
        }
    
        public int Applicant_Status_Id { get; set; }
        public string Applicant_Status_Name { get; set; }
        public string Applicant_Status_Description { get; set; }
    
        public virtual ICollection<APPLICANT> APPLICANT { get; set; }
    }
}
