//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_APPLICATION_APPROVAL
    {
        public long Application_Form_Id { get; set; }
        public bool Is_Approved { get; set; }
        public System.DateTime Date_Treated { get; set; }
        public string Remarks { get; set; }
        public long User_Id { get; set; }
        public string Clearance_Code { get; set; }
    
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual USER USER { get; set; }
    }
}
