//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_CLEARANCE
    {
        public long Application_Form_Id { get; set; }
        public bool Cleared { get; set; }
        public System.DateTime Date_Cleared { get; set; }
    
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
    }
}
