//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_LEVEL
    {
        public long Person_Id { get; set; }
        public int Level_Id { get; set; }
        public int Session_Id { get; set; }
        public long Application_Form_Id { get; set; }
    
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
