//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_FORM_SETTING
    {
        public APPLICATION_FORM_SETTING()
        {
            this.APPLICATION_FORM = new HashSet<APPLICATION_FORM>();
        }
    
        public int Application_Form_Setting_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public int Payment_Type_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public int Session_Id { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public long Entered_By_User_Id { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }
        public string Exam_Venue { get; set; }
        public Nullable<System.TimeSpan> Exam_Time { get; set; }
        public Nullable<System.DateTime> RegistrationEndDate { get; set; }
        public Nullable<System.TimeSpan> RegistrationEndTime { get; set; }
    
        public virtual ICollection<APPLICATION_FORM> APPLICATION_FORM { get; set; }
        public virtual PAYMENT_MODE PAYMENT_MODE { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
