//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT_PREVIOUS_EDUCATION
    {
        public long Applicant_Previous_Education_Id { get; set; }
        public long Person_Id { get; set; }
        public string Previous_School_Name { get; set; }
        public string Previous_Course { get; set; }
        public System.DateTime Previous_Education_Start_Date { get; set; }
        public System.DateTime Previous_Education_End_Date { get; set; }
        public int Educational_Qualification_Id { get; set; }
        public int Result_Grade_Id { get; set; }
        public int IT_Duration_Id { get; set; }
        public Nullable<long> Application_Form_Id { get; set; }
        public Nullable<bool> Convocation_Status { get; set; }
        public Nullable<bool> Certificate_Status { get; set; }
        public string Result_Copy_Url { get; set; }
        public string Certificate_Copy_Url { get; set; }
        public string IT_Letter_Of_Completion { get; set; }
    
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual RESULT_GRADE RESULT_GRADE { get; set; }
        public virtual EDUCATIONAL_QUALIFICATION EDUCATIONAL_QUALIFICATION { get; set; }
        public virtual IT_DURATION IT_DURATION { get; set; }
    }
}
