//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICANT
    {
        public long Application_Form_Id { get; set; }
        public long Person_Id { get; set; }
        public int Ability_Id { get; set; }
        public string Other_Ability { get; set; }
        public string Extra_Curricular_Activities { get; set; }
        public int Applicant_Status_Id { get; set; }
    
        public virtual ABILITY ABILITY { get; set; }
        public virtual APPLICANT_STATUS APPLICANT_STATUS { get; set; }
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
