//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_PAYMENT
    {
        public long Payment_Id { get; set; }
        public long Scratch_Card_Id { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
    
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual SCRATCH_CARD SCRATCH_CARD { get; set; }
    }
}
