//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_ASSESSMENT
    {
        public CLASS_ASSESSMENT()
        {
            this.STUDENT_SCORE = new HashSet<STUDENT_SCORE>();
        }
    
        public long Class_Assessment_Id { get; set; }
        public int Level_Id { get; set; }
        public int Assessment_Criteria_Id { get; set; }
        public int Maximum_Score_Obtainable { get; set; }
        public int Maximum_Percent_Score_Obtainable { get; set; }
        public System.DateTime Date_Entered { get; set; }
    
        public virtual STUDENT_ASSESSMENT_CRITERIA STUDENT_ASSESSMENT_CRITERIA { get; set; }
        public virtual ICollection<STUDENT_SCORE> STUDENT_SCORE { get; set; }
    }
}
