//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_ROOM
    {
        public CLASS_ROOM()
        {
            this.LEVEL_CLASS_ROOM = new HashSet<LEVEL_CLASS_ROOM>();
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
        }
    
        public int Class_Room_Id { get; set; }
        public string Class_Room_Name { get; set; }
        public string Class_Room_Description { get; set; }
    
        public virtual ICollection<LEVEL_CLASS_ROOM> LEVEL_CLASS_ROOM { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
    }
}
