//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLEARANCE_DISPUTES
    {
        public long Id { get; set; }
        public long Clearance_Log_Id { get; set; }
        public string Remark { get; set; }
        public string Attachment { get; set; }
        public bool IsStudent { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual CLEARANCE_LOG CLEARANCE_LOG { get; set; }
    }
}
