//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLEARANCE_STATUS
    {
        public CLEARANCE_STATUS()
        {
            this.CLEARANCE_LOG = new HashSet<CLEARANCE_LOG>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CLEARANCE_LOG> CLEARANCE_LOG { get; set; }
    }
}
