//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLEARANCE_LOG
    {
        public CLEARANCE_LOG()
        {
            this.CLEARANCE_DISPUTES = new HashSet<CLEARANCE_DISPUTES>();
        }
    
        public long Id { get; set; }
        public long Student_Id { get; set; }
        public int Clearance_Status_Id { get; set; }
        public int Clearance_Unit_Id { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> User_Id { get; set; }
        public Nullable<System.DateTime> Date_Cleared { get; set; }
        public string Client { get; set; }
        public bool Closed { get; set; }
    
        public virtual ICollection<CLEARANCE_DISPUTES> CLEARANCE_DISPUTES { get; set; }
        public virtual CLEARANCE_STATUS CLEARANCE_STATUS { get; set; }
        public virtual CLEARANCE_UNITS CLEARANCE_UNITS { get; set; }
        public virtual USER USER { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
