//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFRENCE
    {
        public int Confrence_Id { get; set; }
        public long Person_Id { get; set; }
        public string Department { get; set; }
        public string Institution { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postal_Code { get; set; }
        public string Country { get; set; }
        public string Amount_Package { get; set; }
        public System.DateTime Date_Applied { get; set; }
        public string Status { get; set; }
        public string Research_DocumentURl { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
