//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        public COURSE()
        {
            this.COURSE_ALLOCATION = new HashSet<COURSE_ALLOCATION>();
            this.COURSE_EVALUATION_ANSWER = new HashSet<COURSE_EVALUATION_ANSWER>();
            this.STUDENT_COURSE_REGISTRATION_DETAIL_AUDIT = new HashSet<STUDENT_COURSE_REGISTRATION_DETAIL_AUDIT>();
            this.STUDENT_COURSE_REGISTRATION_DETAIL = new HashSet<STUDENT_COURSE_REGISTRATION_DETAIL>();
            this.STUDENT_EXAM_RAW_SCORE_SHEET_RESULT = new HashSet<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT>();
            this.STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED = new HashSet<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED>();
            this.STUDENT_RESULT_DETAIL = new HashSet<STUDENT_RESULT_DETAIL>();
            this.E_COURSE_CONTENT = new HashSet<E_COURSE_CONTENT>();
            this.E_ASSIGNMENT = new HashSet<E_ASSIGNMENT>();
        }
    
        public long Course_Id { get; set; }
        public int Course_Type_Id { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public int Level_Id { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public int Course_Unit { get; set; }
        public int Semester_Id { get; set; }
        public Nullable<bool> Activated { get; set; }
        public Nullable<int> Programme_Id { get; set; }
    
        public virtual ICollection<COURSE_ALLOCATION> COURSE_ALLOCATION { get; set; }
        public virtual COURSE_TYPE COURSE_TYPE { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DEPARTMENT_OPTION DEPARTMENT_OPTION { get; set; }
        public virtual ICollection<COURSE_EVALUATION_ANSWER> COURSE_EVALUATION_ANSWER { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual ICollection<STUDENT_COURSE_REGISTRATION_DETAIL_AUDIT> STUDENT_COURSE_REGISTRATION_DETAIL_AUDIT { get; set; }
        public virtual ICollection<STUDENT_COURSE_REGISTRATION_DETAIL> STUDENT_COURSE_REGISTRATION_DETAIL { get; set; }
        public virtual ICollection<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT> STUDENT_EXAM_RAW_SCORE_SHEET_RESULT { get; set; }
        public virtual ICollection<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED> STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED { get; set; }
        public virtual ICollection<STUDENT_RESULT_DETAIL> STUDENT_RESULT_DETAIL { get; set; }
        public virtual ICollection<E_COURSE_CONTENT> E_COURSE_CONTENT { get; set; }
        public virtual ICollection<E_ASSIGNMENT> E_ASSIGNMENT { get; set; }
    }
}
