//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE_UNIT
    {
        public int Course_Unit_Id { get; set; }
        public int Department_Id { get; set; }
        public int Level_Id { get; set; }
        public int Semester_Id { get; set; }
        public byte Minimum_Unit { get; set; }
        public byte Maximum_Unit { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public Nullable<int> Programme_Id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual DEPARTMENT_OPTION DEPARTMENT_OPTION { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
    }
}
