//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAY_ACTIVITY
    {
        public int Day_Activity_Id { get; set; }
        public byte Day_Id { get; set; }
        public string Activity { get; set; }
        public int Period_Id { get; set; }
        public Nullable<long> Person_Id { get; set; }
        public long Time_Table_Id { get; set; }
    
        public virtual DAY DAY { get; set; }
        public virtual PERIOD PERIOD { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
