//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVING_EXPERIENCE
    {
        public long Driving_Experience_Id { get; set; }
        public Nullable<long> Application_Form_Id { get; set; }
        public string License_Number { get; set; }
        public int Licence_Type_Id { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<decimal> Height { get; set; }
        public bool Facial_Marks { get; set; }
        public int Years_Of_Experience { get; set; }
        public long Person_Id { get; set; }
    
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual LICENSE_TYPE LICENSE_TYPE { get; set; }
    }
}
