//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_ASSIGNMENT_SUBMISSION
    {
        public long Id { get; set; }
        public long Assignment_Id { get; set; }
        public long Student_Id { get; set; }
        public string Assignment_Content { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Score { get; set; }
        public System.DateTime Date_Submitted { get; set; }
        public string Submission_in_Text { get; set; }
    
        public virtual E_ASSIGNMENT E_ASSIGNMENT { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
