//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_ASSIGNMENT
    {
        public E_ASSIGNMENT()
        {
            this.E_ASSIGNMENT_SUBMISSION = new HashSet<E_ASSIGNMENT_SUBMISSION>();
        }
    
        public long Id { get; set; }
        public long Course_Id { get; set; }
        public string Assignment { get; set; }
        public string Url { get; set; }
        public string Instructions { get; set; }
        public System.DateTime Date_Set { get; set; }
        public System.DateTime Due_Date { get; set; }
        public long Course_Allocation_Id { get; set; }
        public int Max_Score { get; set; }
        public string Assignment_Text { get; set; }
        public bool IsDelete { get; set; }
        public bool Publish { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual COURSE_ALLOCATION COURSE_ALLOCATION { get; set; }
        public virtual ICollection<E_ASSIGNMENT_SUBMISSION> E_ASSIGNMENT_SUBMISSION { get; set; }
    }
}
