//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_CHAT_TOPIC
    {
        public E_CHAT_TOPIC()
        {
            this.E_CHAT_RESPONPSE = new HashSet<E_CHAT_RESPONPSE>();
        }
    
        public long E_Chat_Topic_Id { get; set; }
        public bool Active { get; set; }
        public Nullable<long> Course_Allocation_Id { get; set; }
    
        public virtual COURSE_ALLOCATION COURSE_ALLOCATION { get; set; }
        public virtual ICollection<E_CHAT_RESPONPSE> E_CHAT_RESPONPSE { get; set; }
    }
}
