//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY_OFFICER
    {
        public long User_Id { get; set; }
        public int Faculty_Id { get; set; }
        public string Description { get; set; }
    
        public virtual FACULTY FACULTY { get; set; }
        public virtual USER USER { get; set; }
    }
}
