//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE
    {
        public FEE()
        {
            this.DELIVERY_SERVICE_ZONE = new HashSet<DELIVERY_SERVICE_ZONE>();
            this.FEE_DETAIL_AUDIT = new HashSet<FEE_DETAIL_AUDIT>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.FEESETUP_FEE = new HashSet<FEESETUP_FEE>();
            this.FEE_IN_PAYMENT = new HashSet<FEE_IN_PAYMENT>();
        }
    
        public int Fee_Id { get; set; }
        public string Fee_Name { get; set; }
        public decimal Amount { get; set; }
        public string Fee_Description { get; set; }
    
        public virtual ICollection<DELIVERY_SERVICE_ZONE> DELIVERY_SERVICE_ZONE { get; set; }
        public virtual ICollection<FEE_DETAIL_AUDIT> FEE_DETAIL_AUDIT { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<FEESETUP_FEE> FEESETUP_FEE { get; set; }
        public virtual ICollection<FEE_IN_PAYMENT> FEE_IN_PAYMENT { get; set; }
    }
}
