//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_SETUP_AUDIT
    {
        public int Fee_Setup_Audit_Id { get; set; }
        public int Fee_SetUp_Id { get; set; }
        public int PaymentMode_Id { get; set; }
        public int FeeType_Id { get; set; }
        public int Session_Id { get; set; }
        public decimal Amount { get; set; }
        public string Action { get; set; }
        public string Client { get; set; }
        public long User_Id { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual FEE_SETUP FEE_SETUP { get; set; }
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual PAYMENT_MODE PAYMENT_MODE { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual USER USER { get; set; }
    }
}
