//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEE_DETAIL
    {
        public FEE_DETAIL()
        {
            this.FEE_DETAIL_AUDIT = new HashSet<FEE_DETAIL_AUDIT>();
        }
    
        public int Fee_Detail_Id { get; set; }
        public int Fee_Id { get; set; }
        public Nullable<int> Fee_Type_Id { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public Nullable<int> Payment_Mode_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public int Session_Id { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual FEE FEE { get; set; }
        public virtual ICollection<FEE_DETAIL_AUDIT> FEE_DETAIL_AUDIT { get; set; }
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual PAYMENT_MODE PAYMENT_MODE { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
