//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK_STORE
    {
        public long Id { get; set; }
        public Nullable<long> Live_Lecture_Id { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
    
        public virtual LIVE_LECTURES LIVE_LECTURES { get; set; }
    }
}
