//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTEL_TYPE
    {
        public HOSTEL_TYPE()
        {
            this.HOSTEL = new HashSet<HOSTEL>();
        }
    
        public int Hostel_Type_Id { get; set; }
        public string Hostel_Type_Name { get; set; }
        public string Hostel_Type_Description { get; set; }
    
        public virtual ICollection<HOSTEL> HOSTEL { get; set; }
    }
}
