//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTEL_AMOUNT
    {
        public int Hostel_Amount_Id { get; set; }
        public int Hostel_Id { get; set; }
        public decimal Amount { get; set; }
        public bool Activated { get; set; }
    
        public virtual HOSTEL HOSTEL { get; set; }
    }
}
