//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTEL_FEE
    {
        public long Hostel_Fee_Id { get; set; }
        public long Payment_Id { get; set; }
        public int Hostel_Id { get; set; }
        public double Amount { get; set; }
    
        public virtual HOSTEL HOSTEL { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
    }
}
