//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTEL
    {
        public HOSTEL()
        {
            this.HOSTEL_ALLOCATION_CRITERIA = new HashSet<HOSTEL_ALLOCATION_CRITERIA>();
            this.HOSTEL_ALLOCATION = new HashSet<HOSTEL_ALLOCATION>();
            this.HOSTEL_AMOUNT = new HashSet<HOSTEL_AMOUNT>();
            this.HOSTEL_FEE = new HashSet<HOSTEL_FEE>();
            this.HOSTEL_REQUEST = new HashSet<HOSTEL_REQUEST>();
            this.HOSTEL_ROOM = new HashSet<HOSTEL_ROOM>();
            this.HOSTEL_SERIES = new HashSet<HOSTEL_SERIES>();
        }
    
        public int Hostel_Id { get; set; }
        public int Hostel_Type_Id { get; set; }
        public string Hostel_Name { get; set; }
        public int Capacity { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<HOSTEL_ALLOCATION_CRITERIA> HOSTEL_ALLOCATION_CRITERIA { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION> HOSTEL_ALLOCATION { get; set; }
        public virtual ICollection<HOSTEL_AMOUNT> HOSTEL_AMOUNT { get; set; }
        public virtual ICollection<HOSTEL_FEE> HOSTEL_FEE { get; set; }
        public virtual HOSTEL_TYPE HOSTEL_TYPE { get; set; }
        public virtual ICollection<HOSTEL_REQUEST> HOSTEL_REQUEST { get; set; }
        public virtual ICollection<HOSTEL_ROOM> HOSTEL_ROOM { get; set; }
        public virtual ICollection<HOSTEL_SERIES> HOSTEL_SERIES { get; set; }
    }
}
