//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTITUTION_TYPE
    {
        public INSTITUTION_TYPE()
        {
            this.INSTITUTION = new HashSet<INSTITUTION>();
        }
    
        public int Institution_Type_Id { get; set; }
        public string Institution_Type_Name { get; set; }
        public string Institution_Type_Description { get; set; }
    
        public virtual ICollection<INSTITUTION> INSTITUTION { get; set; }
    }
}
