//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JAMB_O_LEVEL
    {
        public JAMB_O_LEVEL()
        {
            this.JAMB_O_LEVEL_DETAIL = new HashSet<JAMB_O_LEVEL_DETAIL>();
        }
    
        public long Id { get; set; }
        public long Jamb_Record_Id { get; set; }
        public string Exam_Number { get; set; }
        public Nullable<int> Exam_Year { get; set; }
        public int Exam_Sitting { get; set; }
        public int Exam_Type_Id { get; set; }
    
        public virtual ICollection<JAMB_O_LEVEL_DETAIL> JAMB_O_LEVEL_DETAIL { get; set; }
        public virtual O_LEVEL_EXAM_SITTING O_LEVEL_EXAM_SITTING { get; set; }
        public virtual O_LEVEL_TYPE O_LEVEL_TYPE { get; set; }
        public virtual JAMB_RECORD JAMB_RECORD { get; set; }
    }
}
