//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JAMB_RECORD
    {
        public JAMB_RECORD()
        {
            this.JAMB_O_LEVEL = new HashSet<JAMB_O_LEVEL>();
        }
    
        public long Jamb_Record_Id { get; set; }
        public string Jamb_Registration_Number { get; set; }
        public string Candidate_Name { get; set; }
        public string First_Choice_Institution { get; set; }
        public string Subject1 { get; set; }
        public string Subject2 { get; set; }
        public string Subject3 { get; set; }
        public string Subject4 { get; set; }
        public Nullable<short> Total_Jamb_Score { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public string State_Id { get; set; }
        public Nullable<int> Course_Id { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public Nullable<int> Score1 { get; set; }
        public Nullable<int> Score2 { get; set; }
        public Nullable<int> Score3 { get; set; }
        public Nullable<int> Score4 { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<JAMB_O_LEVEL> JAMB_O_LEVEL { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual SEX SEX { get; set; }
        public virtual STATE STATE { get; set; }
    }
}
