//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEVEL_CLASS_ROOM
    {
        public int Level_Class_Room_Id { get; set; }
        public int Level_Id { get; set; }
        public int Class_Room_Id { get; set; }
        public int Class_Capacity { get; set; }
    
        public virtual CLASS_ROOM CLASS_ROOM { get; set; }
    }
}
