//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICENSE_TYPE
    {
        public LICENSE_TYPE()
        {
            this.DRIVING_EXPERIENCE = new HashSet<DRIVING_EXPERIENCE>();
        }
    
        public int License_Type_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<DRIVING_EXPERIENCE> DRIVING_EXPERIENCE { get; set; }
    }
}
