//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVE_LECTURES
    {
        public LIVE_LECTURES()
        {
            this.LIVE_LECTURE_ATTENDANCE = new HashSet<LIVE_LECTURE_ATTENDANCE>();
            this.FEEDBACK_STORE = new HashSet<FEEDBACK_STORE>();
        }
    
        public long Id { get; set; }
        public long Course_Allocation_Id { get; set; }
        public string Topic { get; set; }
        public string Agenda { get; set; }
        public int Duration { get; set; }
        public Nullable<System.DateTime> Lecture_Date { get; set; }
        public Nullable<int> Time { get; set; }
        public string Start_Meeting_Url { get; set; }
        public string Join_Meeting_Url { get; set; }
        public System.DateTime Date_Created { get; set; }
        public int Department_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Session_Id { get; set; }
        public Nullable<int> Level_Id { get; set; }
    
        public virtual COURSE_ALLOCATION COURSE_ALLOCATION { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual LEVEL LEVEL { get; set; }
        public virtual ICollection<LIVE_LECTURE_ATTENDANCE> LIVE_LECTURE_ATTENDANCE { get; set; }
        public virtual PROGRAMME PROGRAMME { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual ICollection<FEEDBACK_STORE> FEEDBACK_STORE { get; set; }
    }
}
