//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVE_LECTURE_ATTENDANCE
    {
        public long Id { get; set; }
        public long Student_Id { get; set; }
        public long Student_Course_Registration_Detail_Id { get; set; }
        public long Live_Lecture_Id { get; set; }
    
        public virtual LIVE_LECTURES LIVE_LECTURES { get; set; }
        public virtual STUDENT_COURSE_REGISTRATION_DETAIL STUDENT_COURSE_REGISTRATION_DETAIL { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
