//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODE_OF_STUDY
    {
        public MODE_OF_STUDY()
        {
            this.STUDENT_ACADEMIC_INFORMATION = new HashSet<STUDENT_ACADEMIC_INFORMATION>();
        }
    
        public int Mode_Of_Study_Id { get; set; }
        public string Mode_Of_Study_Name { get; set; }
        public string Mode_Of_Study_Description { get; set; }
    
        public virtual ICollection<STUDENT_ACADEMIC_INFORMATION> STUDENT_ACADEMIC_INFORMATION { get; set; }
    }
}
