//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODE_OF_FINANCE
    {
        public MODE_OF_FINANCE()
        {
            this.STUDENT_FINANCE_INFORMATION = new HashSet<STUDENT_FINANCE_INFORMATION>();
        }
    
        public int Mode_Of_Finance_Id { get; set; }
        public string Mode_Of_Finance_Name { get; set; }
        public string Mode_Of_Finance_Description { get; set; }
    
        public virtual ICollection<STUDENT_FINANCE_INFORMATION> STUDENT_FINANCE_INFORMATION { get; set; }
    }
}
