//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEXT_OF_KIN
    {
        public long Person_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public int Relationship_Id { get; set; }
        public string Sponsor_Name { get; set; }
        public string Sponsor_Contact_Address { get; set; }
        public string Sponsor_Mobile_Phone { get; set; }
        public Nullable<long> Application_Form_Id { get; set; }
    
        public virtual APPLICATION_FORM APPLICATION_FORM { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual RELATIONSHIP RELATIONSHIP { get; set; }
    }
}
