//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_LEVEL_EXAM_SITTING
    {
        public O_LEVEL_EXAM_SITTING()
        {
            this.APPLICANT_O_LEVEL_RESULT = new HashSet<APPLICANT_O_LEVEL_RESULT>();
            this.APPLICANT_O_LEVEL_RESULT_AUDIT = new HashSet<APPLICANT_O_LEVEL_RESULT_AUDIT>();
            this.JAMB_O_LEVEL = new HashSet<JAMB_O_LEVEL>();
        }
    
        public int O_Level_Exam_Sitting_Id { get; set; }
        public string O_Level_Exam_Sitting_Name { get; set; }
    
        public virtual ICollection<APPLICANT_O_LEVEL_RESULT> APPLICANT_O_LEVEL_RESULT { get; set; }
        public virtual ICollection<APPLICANT_O_LEVEL_RESULT_AUDIT> APPLICANT_O_LEVEL_RESULT_AUDIT { get; set; }
        public virtual ICollection<JAMB_O_LEVEL> JAMB_O_LEVEL { get; set; }
    }
}
