//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONLINE_PAYMENT
    {
        public long Payment_Id { get; set; }
        public int Payment_Channnel_Id { get; set; }
        public string Transaction_Number { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
    
        public virtual PAYMENT_CHANNEL PAYMENT_CHANNEL { get; set; }
        public virtual PAYMENT PAYMENT { get; set; }
        public virtual PAYMENT_ETRANZACT PAYMENT_ETRANZACT { get; set; }
    }
}
