//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_CHANNEL
    {
        public PAYMENT_CHANNEL()
        {
            this.ONLINE_PAYMENT = new HashSet<ONLINE_PAYMENT>();
        }
    
        public int Payment_Channnel_Id { get; set; }
        public string Payment_Channel_Name { get; set; }
        public string Payment_Channel_Description { get; set; }
        public bool Payment_Channel_Status { get; set; }
    
        public virtual ICollection<ONLINE_PAYMENT> ONLINE_PAYMENT { get; set; }
    }
}
