//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_SCHOLARSHIP
    {
        public long Id { get; set; }
        public long Person_Id { get; set; }
        public int Session_id { get; set; }
        public decimal Amount { get; set; }
        public string Scholarship_Name { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual SESSION SESSION { get; set; }
    }
}
