//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_MODE
    {
        public PAYMENT_MODE()
        {
            this.APPLICATION_FORM_SETTING = new HashSet<APPLICATION_FORM_SETTING>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.PAYMENT = new HashSet<PAYMENT>();
            this.PAYMENT_ETRANZACT_TYPE = new HashSet<PAYMENT_ETRANZACT_TYPE>();
            this.FEE_SETUP = new HashSet<FEE_SETUP>();
            this.FEE_SETUP_AUDIT = new HashSet<FEE_SETUP_AUDIT>();
        }
    
        public int Payment_Mode_Id { get; set; }
        public string Payment_Mode_Name { get; set; }
        public string Payment_Mode_Description { get; set; }
    
        public virtual ICollection<APPLICATION_FORM_SETTING> APPLICATION_FORM_SETTING { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<PAYMENT_ETRANZACT_TYPE> PAYMENT_ETRANZACT_TYPE { get; set; }
        public virtual ICollection<FEE_SETUP> FEE_SETUP { get; set; }
        public virtual ICollection<FEE_SETUP_AUDIT> FEE_SETUP_AUDIT { get; set; }
    }
}
