//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public PAYMENT()
        {
            this.APPLICATION_FORM = new HashSet<APPLICATION_FORM>();
            this.HOSTEL_ALLOCATION = new HashSet<HOSTEL_ALLOCATION>();
            this.HOSTEL_FEE = new HashSet<HOSTEL_FEE>();
            this.HOSTEL_REQUEST = new HashSet<HOSTEL_REQUEST>();
            this.SHORT_FALL = new HashSet<SHORT_FALL>();
            this.FEE_IN_PAYMENT = new HashSet<FEE_IN_PAYMENT>();
            this.TRANSCRIPT_REQUEST = new HashSet<TRANSCRIPT_REQUEST>();
        }
    
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public int Payment_Type_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public Nullable<long> Payment_Serial_Number { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Date_Paid { get; set; }
        public Nullable<int> Session_Id { get; set; }
    
        public virtual ICollection<APPLICATION_FORM> APPLICATION_FORM { get; set; }
        public virtual CARD_PAYMENT CARD_PAYMENT { get; set; }
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION> HOSTEL_ALLOCATION { get; set; }
        public virtual ICollection<HOSTEL_FEE> HOSTEL_FEE { get; set; }
        public virtual ICollection<HOSTEL_REQUEST> HOSTEL_REQUEST { get; set; }
        public virtual ONLINE_PAYMENT ONLINE_PAYMENT { get; set; }
        public virtual PAYMENT_MODE PAYMENT_MODE { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
        public virtual PAYMENT_PAYSTACK PAYMENT_PAYSTACK { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual PAYMENT_VERIFICATION PAYMENT_VERIFICATION { get; set; }
        public virtual REMITA_PAYMENT REMITA_PAYMENT { get; set; }
        public virtual ICollection<SHORT_FALL> SHORT_FALL { get; set; }
        public virtual STUDENT_PAYMENT STUDENT_PAYMENT { get; set; }
        public virtual ICollection<FEE_IN_PAYMENT> FEE_IN_PAYMENT { get; set; }
        public virtual ICollection<TRANSCRIPT_REQUEST> TRANSCRIPT_REQUEST { get; set; }
    }
}
