//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_ETRANZACT
    {
        public long Payment_Id { get; set; }
        public int Payment_Etranzact_Type_Id { get; set; }
        public long Payment_Terminal_Id { get; set; }
        public string Receipt_No { get; set; }
        public string Payment_Code { get; set; }
        public string Merchant_Code { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
        public string Transaction_Description { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Confirmation_No { get; set; }
        public string Bank_Code { get; set; }
        public string Branch_Code { get; set; }
        public string Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Address { get; set; }
        public Nullable<bool> Used { get; set; }
        public Nullable<long> Used_By_Person_Id { get; set; }
    
        public virtual ONLINE_PAYMENT ONLINE_PAYMENT { get; set; }
        public virtual PAYMENT_ETRANZACT_TYPE PAYMENT_ETRANZACT_TYPE { get; set; }
        public virtual PAYMENT_TERMINAL PAYMENT_TERMINAL { get; set; }
    }
}
