//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public PERSON()
        {
            this.APPLICANT = new HashSet<APPLICANT>();
            this.APPLICANT_O_LEVEL_RESULT = new HashSet<APPLICANT_O_LEVEL_RESULT>();
            this.APPLICANT_O_LEVEL_RESULT_AUDIT = new HashSet<APPLICANT_O_LEVEL_RESULT_AUDIT>();
            this.APPLICATION_FORM = new HashSet<APPLICATION_FORM>();
            this.CHANGE_OF_COURSE = new HashSet<CHANGE_OF_COURSE>();
            this.CHANGE_OF_COURSE1 = new HashSet<CHANGE_OF_COURSE>();
            this.CONFRENCE = new HashSet<CONFRENCE>();
            this.HOSTEL_ALLOCATION = new HashSet<HOSTEL_ALLOCATION>();
            this.HOSTEL_REQUEST = new HashSet<HOSTEL_REQUEST>();
            this.PAYMENT = new HashSet<PAYMENT>();
            this.PAYMENT_SCHOLARSHIP = new HashSet<PAYMENT_SCHOLARSHIP>();
            this.PERSON_AUDIT = new HashSet<PERSON_AUDIT>();
            this.RANKING_DATA = new HashSet<RANKING_DATA>();
            this.SCRATCH_CARD = new HashSet<SCRATCH_CARD>();
            this.STUDENT_EXTRA_YEAR_SESSION = new HashSet<STUDENT_EXTRA_YEAR_SESSION>();
            this.E_COURSE_CONTENT_DOWNLOAD = new HashSet<E_COURSE_CONTENT_DOWNLOAD>();
            this.APPLICANT_PREVIOUS_EDUCATION = new HashSet<APPLICANT_PREVIOUS_EDUCATION>();
            this.DRIVING_EXPERIENCE = new HashSet<DRIVING_EXPERIENCE>();
        }
    
        public long Person_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Initial { get; set; }
        public string Title { get; set; }
        public string Image_File_Url { get; set; }
        public string Signature_File_Url { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public string Contact_Address { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string State_Id { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Home_Town { get; set; }
        public string Home_Address { get; set; }
        public int Nationality_Id { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public int Role_Id { get; set; }
    
        public virtual ICollection<APPLICANT> APPLICANT { get; set; }
        public virtual APPLICANT_APPLIED_COURSE APPLICANT_APPLIED_COURSE { get; set; }
        public virtual APPLICANT_JAMB_DETAIL APPLICANT_JAMB_DETAIL { get; set; }
        public virtual APPLICANT_LEVEL APPLICANT_LEVEL { get; set; }
        public virtual ICollection<APPLICANT_O_LEVEL_RESULT> APPLICANT_O_LEVEL_RESULT { get; set; }
        public virtual ICollection<APPLICANT_O_LEVEL_RESULT_AUDIT> APPLICANT_O_LEVEL_RESULT_AUDIT { get; set; }
        public virtual APPLICANT_SPONSOR APPLICANT_SPONSOR { get; set; }
        public virtual ICollection<APPLICATION_FORM> APPLICATION_FORM { get; set; }
        public virtual ICollection<CHANGE_OF_COURSE> CHANGE_OF_COURSE { get; set; }
        public virtual ICollection<CHANGE_OF_COURSE> CHANGE_OF_COURSE1 { get; set; }
        public virtual ICollection<CONFRENCE> CONFRENCE { get; set; }
        public virtual ICollection<HOSTEL_ALLOCATION> HOSTEL_ALLOCATION { get; set; }
        public virtual ICollection<HOSTEL_REQUEST> HOSTEL_REQUEST { get; set; }
        public virtual LOCAL_GOVERNMENT LOCAL_GOVERNMENT { get; set; }
        public virtual LOCAL_GOVERNMENT LOCAL_GOVERNMENT1 { get; set; }
        public virtual NATIONALITY NATIONALITY { get; set; }
        public virtual NATIONALITY NATIONALITY1 { get; set; }
        public virtual NEXT_OF_KIN NEXT_OF_KIN { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<PAYMENT_SCHOLARSHIP> PAYMENT_SCHOLARSHIP { get; set; }
        public virtual ICollection<PERSON_AUDIT> PERSON_AUDIT { get; set; }
        public virtual PERSON_LOGIN PERSON_LOGIN { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE1 { get; set; }
        public virtual RELIGION RELIGION { get; set; }
        public virtual RELIGION RELIGION1 { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual ROLE ROLE1 { get; set; }
        public virtual SEX SEX { get; set; }
        public virtual SEX SEX1 { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual STATE STATE1 { get; set; }
        public virtual ICollection<RANKING_DATA> RANKING_DATA { get; set; }
        public virtual ICollection<SCRATCH_CARD> SCRATCH_CARD { get; set; }
        public virtual STAFF STAFF { get; set; }
        public virtual ICollection<STUDENT_EXTRA_YEAR_SESSION> STUDENT_EXTRA_YEAR_SESSION { get; set; }
        public virtual ICollection<E_COURSE_CONTENT_DOWNLOAD> E_COURSE_CONTENT_DOWNLOAD { get; set; }
        public virtual ICollection<APPLICANT_PREVIOUS_EDUCATION> APPLICANT_PREVIOUS_EDUCATION { get; set; }
        public virtual ICollection<DRIVING_EXPERIENCE> DRIVING_EXPERIENCE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
