//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_AUDIT
    {
        public long Person_Audit_Id { get; set; }
        public long Person_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Initial { get; set; }
        public string Title { get; set; }
        public string Image_File_Url { get; set; }
        public string Signature_File_Url { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public string Contact_Address { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string State_Id { get; set; }
        public Nullable<int> Local_Government_Id { get; set; }
        public string Home_Town { get; set; }
        public string Home_Address { get; set; }
        public Nullable<int> Nationality_Id { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public Nullable<System.DateTime> Date_Entered { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<int> Old_Person_Type_Id { get; set; }
        public string Old_First_Name { get; set; }
        public string Old_Last_Name { get; set; }
        public string Old_Other_Name { get; set; }
        public string Old_Initial { get; set; }
        public string Old_Title { get; set; }
        public string Old_Image_File_Url { get; set; }
        public string Old_Signature_File_Url { get; set; }
        public Nullable<byte> Old_Sex_Id { get; set; }
        public string Old_Contact_Address { get; set; }
        public string Old_Email { get; set; }
        public string Old_Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Old_Date_Of_Birth { get; set; }
        public string Old_State_Id { get; set; }
        public Nullable<int> Old_Local_Government_Id { get; set; }
        public string Old_Home_Town { get; set; }
        public string Old_Home_Address { get; set; }
        public Nullable<int> Old_Nationality_Id { get; set; }
        public Nullable<int> Old_Religion_Id { get; set; }
        public Nullable<System.DateTime> Old_Date_Entered { get; set; }
        public Nullable<int> Old_Role_Id { get; set; }
        public long User_Id { get; set; }
        public string Operation { get; set; }
        public string Action { get; set; }
        public System.DateTime Time { get; set; }
        public string Client { get; set; }
    
        public virtual LOCAL_GOVERNMENT LOCAL_GOVERNMENT { get; set; }
        public virtual LOCAL_GOVERNMENT LOCAL_GOVERNMENT1 { get; set; }
        public virtual NATIONALITY NATIONALITY { get; set; }
        public virtual NATIONALITY NATIONALITY1 { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE { get; set; }
        public virtual PERSON_TYPE PERSON_TYPE1 { get; set; }
        public virtual RELIGION RELIGION { get; set; }
        public virtual RELIGION RELIGION1 { get; set; }
        public virtual ROLE ROLE { get; set; }
        public virtual ROLE ROLE1 { get; set; }
        public virtual SEX SEX { get; set; }
        public virtual SEX SEX1 { get; set; }
        public virtual STATE STATE { get; set; }
        public virtual STATE STATE1 { get; set; }
        public virtual USER USER { get; set; }
    }
}
