//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMME
    {
        public PROGRAMME()
        {
            this.ADMISSION_CRITERIA = new HashSet<ADMISSION_CRITERIA>();
            this.APPLICANT_APPLIED_COURSE = new HashSet<APPLICANT_APPLIED_COURSE>();
            this.APPLICANT_APPLIED_COURSE_AUDIT = new HashSet<APPLICANT_APPLIED_COURSE_AUDIT>();
            this.APPLICANT_APPLIED_COURSE_AUDIT1 = new HashSet<APPLICANT_APPLIED_COURSE_AUDIT>();
            this.APPLICATION_PROGRAMME_FEE = new HashSet<APPLICATION_PROGRAMME_FEE>();
            this.COMPLAIN_LOG = new HashSet<COMPLAIN_LOG>();
            this.COURSE = new HashSet<COURSE>();
            this.COURSE_ALLOCATION = new HashSet<COURSE_ALLOCATION>();
            this.COURSE_REGISTRATION_STATUS = new HashSet<COURSE_REGISTRATION_STATUS>();
            this.COURSE_UNIT = new HashSet<COURSE_UNIT>();
            this.DEPARTMENT_CAPACITY = new HashSet<DEPARTMENT_CAPACITY>();
            this.FEE_DETAIL = new HashSet<FEE_DETAIL>();
            this.FEE_DETAIL_AUDIT = new HashSet<FEE_DETAIL_AUDIT>();
            this.HOSTEL_BLACKLIST = new HashSet<HOSTEL_BLACKLIST>();
            this.HOSTEL_REQUEST = new HashSet<HOSTEL_REQUEST>();
            this.PAYMENT_ETRANZACT_TYPE = new HashSet<PAYMENT_ETRANZACT_TYPE>();
            this.PROGRAMME_DEPARTMENT = new HashSet<PROGRAMME_DEPARTMENT>();
            this.STUDENT_COURSE_REGISTRATION = new HashSet<STUDENT_COURSE_REGISTRATION>();
            this.STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED = new HashSet<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED>();
            this.STUDENT_LEVEL = new HashSet<STUDENT_LEVEL>();
            this.STUDENT_MATRIC_NUMBER_ASSIGNMENT = new HashSet<STUDENT_MATRIC_NUMBER_ASSIGNMENT>();
            this.STUDENT_RESULT = new HashSet<STUDENT_RESULT>();
            this.VENUE_DESIGNATION = new HashSet<VENUE_DESIGNATION>();
            this.STUDENT_RESULT_STATUS = new HashSet<STUDENT_RESULT_STATUS>();
            this.LIVE_LECTURES = new HashSet<LIVE_LECTURES>();
        }
    
        public int Programme_Id { get; set; }
        public string Programme_Name { get; set; }
        public string Programme_Description { get; set; }
        public string Programme_Short_Name { get; set; }
        public Nullable<bool> Activated { get; set; }
        public bool ActiveFor_Application { get; set; }
    
        public virtual ICollection<ADMISSION_CRITERIA> ADMISSION_CRITERIA { get; set; }
        public virtual ICollection<APPLICANT_APPLIED_COURSE> APPLICANT_APPLIED_COURSE { get; set; }
        public virtual ICollection<APPLICANT_APPLIED_COURSE_AUDIT> APPLICANT_APPLIED_COURSE_AUDIT { get; set; }
        public virtual ICollection<APPLICANT_APPLIED_COURSE_AUDIT> APPLICANT_APPLIED_COURSE_AUDIT1 { get; set; }
        public virtual ICollection<APPLICATION_PROGRAMME_FEE> APPLICATION_PROGRAMME_FEE { get; set; }
        public virtual ICollection<COMPLAIN_LOG> COMPLAIN_LOG { get; set; }
        public virtual ICollection<COURSE> COURSE { get; set; }
        public virtual ICollection<COURSE_ALLOCATION> COURSE_ALLOCATION { get; set; }
        public virtual ICollection<COURSE_REGISTRATION_STATUS> COURSE_REGISTRATION_STATUS { get; set; }
        public virtual ICollection<COURSE_UNIT> COURSE_UNIT { get; set; }
        public virtual ICollection<DEPARTMENT_CAPACITY> DEPARTMENT_CAPACITY { get; set; }
        public virtual ICollection<FEE_DETAIL> FEE_DETAIL { get; set; }
        public virtual ICollection<FEE_DETAIL_AUDIT> FEE_DETAIL_AUDIT { get; set; }
        public virtual ICollection<HOSTEL_BLACKLIST> HOSTEL_BLACKLIST { get; set; }
        public virtual ICollection<HOSTEL_REQUEST> HOSTEL_REQUEST { get; set; }
        public virtual ICollection<PAYMENT_ETRANZACT_TYPE> PAYMENT_ETRANZACT_TYPE { get; set; }
        public virtual ICollection<PROGRAMME_DEPARTMENT> PROGRAMME_DEPARTMENT { get; set; }
        public virtual ICollection<STUDENT_COURSE_REGISTRATION> STUDENT_COURSE_REGISTRATION { get; set; }
        public virtual ICollection<STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED> STUDENT_EXAM_RAW_SCORE_SHEET_RESULT_NOT_REGISTERED { get; set; }
        public virtual ICollection<STUDENT_LEVEL> STUDENT_LEVEL { get; set; }
        public virtual ICollection<STUDENT_MATRIC_NUMBER_ASSIGNMENT> STUDENT_MATRIC_NUMBER_ASSIGNMENT { get; set; }
        public virtual ICollection<STUDENT_RESULT> STUDENT_RESULT { get; set; }
        public virtual ICollection<VENUE_DESIGNATION> VENUE_DESIGNATION { get; set; }
        public virtual ICollection<STUDENT_RESULT_STATUS> STUDENT_RESULT_STATUS { get; set; }
        public virtual ICollection<LIVE_LECTURES> LIVE_LECTURES { get; set; }
    }
}
