//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RANKING_DATA1
    {
        public long Id { get; set; }
        public long Person_id { get; set; }
        public string Subj1 { get; set; }
        public string Subj2 { get; set; }
        public string Subj3 { get; set; }
        public string Subj4 { get; set; }
        public string Subj5 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Qualified { get; set; }
        public string Reason { get; set; }
    
        public virtual PERSON PERSON { get; set; }
    }
}
