//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGENERATED_CLEARED_INVOICE
    {
        public long Id { get; set; }
        public long PaymentId { get; set; }
        public long PersonId { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
        public System.DateTime Date_Created { get; set; }
        public string Invoice_Number { get; set; }
        public string Reference_Number { get; set; }
        public int FeeType_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public string Description { get; set; }
        public string Order_Id { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public int Session_Id { get; set; }
    }
}
