//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIGHT
    {
        public RIGHT()
        {
            this.ROLE_RIGHT = new HashSet<ROLE_RIGHT>();
        }
    
        public int Right_Id { get; set; }
        public string Right_Name { get; set; }
        public string Right_Description { get; set; }
    
        public virtual ICollection<ROLE_RIGHT> ROLE_RIGHT { get; set; }
    }
}
