//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCORE_GRADE
    {
        public int Grade_Id { get; set; }
        public int Score_From { get; set; }
        public int Score_To { get; set; }
        public string Grade { get; set; }
        public decimal Grade_Point { get; set; }
        public string Performance { get; set; }
        public string Grade_Description { get; set; }
        public string Session_Start { get; set; }
    }
}
