//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRATCH_CARD
    {
        public SCRATCH_CARD()
        {
            this.CARD_PAYMENT = new HashSet<CARD_PAYMENT>();
        }
    
        public long Scratch_Card_Id { get; set; }
        public long Scratch_Card_Batch_Id { get; set; }
        public string Serial_Number { get; set; }
        public string Pin { get; set; }
        public byte Usage_Count { get; set; }
        public Nullable<System.DateTime> First_Used_Date { get; set; }
        public Nullable<long> Person_Id { get; set; }
    
        public virtual ICollection<CARD_PAYMENT> CARD_PAYMENT { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual SCRATCH_CARD_BATCH SCRATCH_CARD_BATCH { get; set; }
    }
}
