//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRATCH_CARD_TYPE
    {
        public SCRATCH_CARD_TYPE()
        {
            this.SCRATCH_CARD_BATCH = new HashSet<SCRATCH_CARD_BATCH>();
        }
    
        public int Scratch_Card_Type_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public string Scratch_Card_Type_Name { get; set; }
        public string Scratch_Card_Type_Description { get; set; }
    
        public virtual FEE_TYPE FEE_TYPE { get; set; }
        public virtual ICollection<SCRATCH_CARD_BATCH> SCRATCH_CARD_BATCH { get; set; }
    }
}
