//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEX
    {
        public SEX()
        {
            this.HOSTEL_ALLOCATION_COUNT = new HashSet<HOSTEL_ALLOCATION_COUNT>();
            this.HOSTEL_REQUEST_COUNT = new HashSet<HOSTEL_REQUEST_COUNT>();
            this.PERSON = new HashSet<PERSON>();
            this.PERSON1 = new HashSet<PERSON>();
            this.PERSON_AUDIT = new HashSet<PERSON_AUDIT>();
            this.PERSON_AUDIT1 = new HashSet<PERSON_AUDIT>();
            this.JAMB_RECORD = new HashSet<JAMB_RECORD>();
        }
    
        public byte Sex_Id { get; set; }
        public string Sex_Name { get; set; }
    
        public virtual ICollection<HOSTEL_ALLOCATION_COUNT> HOSTEL_ALLOCATION_COUNT { get; set; }
        public virtual ICollection<HOSTEL_REQUEST_COUNT> HOSTEL_REQUEST_COUNT { get; set; }
        public virtual ICollection<PERSON> PERSON { get; set; }
        public virtual ICollection<PERSON> PERSON1 { get; set; }
        public virtual ICollection<PERSON_AUDIT> PERSON_AUDIT { get; set; }
        public virtual ICollection<PERSON_AUDIT> PERSON_AUDIT1 { get; set; }
        public virtual ICollection<JAMB_RECORD> JAMB_RECORD { get; set; }
    }
}
