//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF
    {
        public STAFF()
        {
            this.COURSE_TEACHER = new HashSet<COURSE_TEACHER>();
            this.DAY_ACTIVITY = new HashSet<DAY_ACTIVITY>();
            this.DEPARTMENT_HEAD = new HashSet<DEPARTMENT_HEAD>();
            this.NEWS = new HashSet<NEWS>();
            this.REPORT_CARD_COMMENT = new HashSet<REPORT_CARD_COMMENT>();
            this.STAFF_DEPARTMENT = new HashSet<STAFF_DEPARTMENT>();
            this.STAFF_JOB_ROLE = new HashSet<STAFF_JOB_ROLE>();
            this.STUDENT_COURSE_REGISTRATION = new HashSet<STUDENT_COURSE_REGISTRATION>();
            this.STUDENT_SCORE = new HashSet<STUDENT_SCORE>();
        }
    
        public long Staff_Id { get; set; }
        public int Staff_Type_Id { get; set; }
        public int Marital_Status_Id { get; set; }
        public string Profile_Description { get; set; }
        public Nullable<long> User_Id { get; set; }
    
        public virtual ICollection<COURSE_TEACHER> COURSE_TEACHER { get; set; }
        public virtual ICollection<DAY_ACTIVITY> DAY_ACTIVITY { get; set; }
        public virtual ICollection<DEPARTMENT_HEAD> DEPARTMENT_HEAD { get; set; }
        public virtual MARITAL_STATUS MARITAL_STATUS { get; set; }
        public virtual ICollection<NEWS> NEWS { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<REPORT_CARD_COMMENT> REPORT_CARD_COMMENT { get; set; }
        public virtual ICollection<STAFF_DEPARTMENT> STAFF_DEPARTMENT { get; set; }
        public virtual ICollection<STAFF_JOB_ROLE> STAFF_JOB_ROLE { get; set; }
        public virtual STAFF_TYPE STAFF_TYPE { get; set; }
        public virtual ICollection<STUDENT_COURSE_REGISTRATION> STUDENT_COURSE_REGISTRATION { get; set; }
        public virtual ICollection<STUDENT_SCORE> STUDENT_SCORE { get; set; }
        public virtual USER USER { get; set; }
    }
}
