//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFF_DEPARTMENT
    {
        public long Staff_Department_Id { get; set; }
        public long Staff_Id { get; set; }
        public int Department_Id { get; set; }
        public int Session_Semester_Id { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public bool IsHead { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual SESSION_SEMESTER SESSION_SEMESTER { get; set; }
        public virtual STAFF STAFF { get; set; }
    }
}
