//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE_GEO_ZONE
    {
        public int State_Geo_Zone_Id { get; set; }
        public string State_Id { get; set; }
        public int Geo_Zone_Id { get; set; }
        public bool Activated { get; set; }
    
        public virtual GEO_ZONE GEO_ZONE { get; set; }
        public virtual STATE STATE { get; set; }
    }
}
