//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_FINANCE_INFORMATION
    {
        public long Person_Id { get; set; }
        public int Mode_Of_Finance_Id { get; set; }
        public string Scholarship_Title { get; set; }
    
        public virtual MODE_OF_FINANCE MODE_OF_FINANCE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
