//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_LEVEL_HISTORY
    {
        public long Student_Level_History_Id { get; set; }
        public long Student_Level_Id { get; set; }
        public System.DateTime Date_Entered { get; set; }
    }
}
