//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ASSESSMENT_CRITERIA
    {
        public STUDENT_ASSESSMENT_CRITERIA()
        {
            this.CLASS_ASSESSMENT = new HashSet<CLASS_ASSESSMENT>();
        }
    
        public int Assessment_Criteria_Id { get; set; }
        public string Assessment_Criteria_Name { get; set; }
        public string Assessment_Criteria_Label { get; set; }
    
        public virtual ICollection<CLASS_ASSESSMENT> CLASS_ASSESSMENT { get; set; }
    }
}
