//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_ACADEMIC_INFORMATION
    {
        public long Person_Id { get; set; }
        public int Mode_Of_Entry_Id { get; set; }
        public int Mode_Of_Study_Id { get; set; }
        public int Year_Of_Admission { get; set; }
        public int Year_Of_Graduation { get; set; }
        public int Level_Id { get; set; }
        public Nullable<System.DateTime> Graduation_Date { get; set; }
        public Nullable<System.DateTime> Transcript_Date { get; set; }
    
        public virtual LEVEL LEVEL { get; set; }
        public virtual MODE_OF_ENTRY MODE_OF_ENTRY { get; set; }
        public virtual MODE_OF_STUDY MODE_OF_STUDY { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
