//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_TYPE
    {
        public STUDENT_TYPE()
        {
            this.STUDENT = new HashSet<STUDENT>();
        }
    
        public int Student_Type_Id { get; set; }
        public string Student_Type_Name { get; set; }
        public string Student_Type_Description { get; set; }
    
        public virtual ICollection<STUDENT> STUDENT { get; set; }
    }
}
