//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_EXTRA_YEAR_SESSION
    {
        public long Student_Extra_Year_Session_Id { get; set; }
        public long Person_Id { get; set; }
        public int Sessions_Registered { get; set; }
        public int Last_Session_Registered { get; set; }
        public int Session_Id { get; set; }
        public Nullable<int> Differement_Commenced_Session { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual SESSION SESSION1 { get; set; }
        public virtual SESSION SESSION2 { get; set; }
    }
}
