//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_DEFERMENT_LOG
    {
        public long Student_Deferment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Session_Id { get; set; }
        public Nullable<int> Semester_Id { get; set; }
        public bool Rusticated { get; set; }
    
        public virtual SEMESTER SEMESTER { get; set; }
        public virtual SESSION SESSION { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
