//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT_SEMESTER
    {
        public long Student_Term_Id { get; set; }
        public long Person_Id { get; set; }
        public int Session_Term_Id { get; set; }
    
        public virtual SESSION_SEMESTER SESSION_SEMESTER { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
