//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ADMISSION_AUDIT
    {
        public string Action { get; set; }
        public string Client { get; set; }
        public string Operation { get; set; }
        public System.DateTime Time { get; set; }
        public long Application_Form_Id { get; set; }
        public string Application_Form_Number { get; set; }
        public int Session_Id { get; set; }
        public long User_Id { get; set; }
        public string User_Name { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Super_Admin { get; set; }
        public int Role_Id { get; set; }
        public string Role_Name { get; set; }
    }
}
