//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ALL_PAYMENT_REPORT_RETURNING_STUDENT
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public string Matric_Number { get; set; }
        public Nullable<decimal> APPLICATION_FEE_AMOUNT { get; set; }
        public Nullable<decimal> ACCEPTANCE_FEE_AMOUNT { get; set; }
        public string FIRST_YEAR_SCHOOL_FEE_AMOUNT { get; set; }
        public Nullable<decimal> SECOND_YEAR_SCHOOL_FEE_AMOUNT { get; set; }
        public long Student_Level_Id { get; set; }
        public long Person_Id { get; set; }
        public int Level_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public int Session_Id { get; set; }
        public string Department_Name { get; set; }
        public string Programme_Name { get; set; }
        public string Level_Name { get; set; }
        public string Session_Name { get; set; }
        public string APPLICATION_FORM_INVOICE { get; set; }
        public string ACCEPTANCE_FEE_INVOICE { get; set; }
        public string FIRST_YEAR_FEE_INVOICE { get; set; }
        public string SECOND_YEAR_FEE_INVOICE { get; set; }
    }
}
