//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_APPLICANT_PAYMENT
    {
        public Nullable<long> Application_Form_Id { get; set; }
        public Nullable<long> Serial_Number { get; set; }
        public string Application_Form_Number { get; set; }
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public int Payment_Type_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public string Transaction_Number { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<long> Scratch_Card_Id { get; set; }
        public Nullable<System.DateTime> Scratch_Card_Use_Date { get; set; }
        public Nullable<long> Payment_Serial_Number { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Date_Paid { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public Nullable<int> Payment_Channnel_Id { get; set; }
        public string Payment_Channel_Name { get; set; }
        public int Fee_Type_Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
