//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ADMISSION_LIST
    {
        public int Department_Id { get; set; }
        public string Department_Code { get; set; }
        public string Department_Name { get; set; }
        public string Application_Form_Number { get; set; }
        public string Application_Exam_Number { get; set; }
        public string FullName { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public string Sex_Name { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public string Session_Name { get; set; }
        public long Person_Id { get; set; }
        public string Programme_Name { get; set; }
        public int Programme_Id { get; set; }
        public string Programme_Short_Name { get; set; }
    }
}
