//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ACCEPTANCE_REPORT
    {
        public string SURNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string OTHER_NAMES { get; set; }
        public string Application_Form_Number { get; set; }
        public string Invoice_Number { get; set; }
        public string Department_Name { get; set; }
        public string Programme_Name { get; set; }
        public long Person_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public string Session_Name { get; set; }
        public int Expr1 { get; set; }
        public int Department_Id { get; set; }
        public long Application_Form_Id { get; set; }
        public string Application_Exam_Number { get; set; }
        public int Programme_Id { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public System.DateTime Date_Paid { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public string Confirmation_No { get; set; }
    }
}
