//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_APPLICATION_FORM_COUNT
    {
        public long Application_Form_Id { get; set; }
        public Nullable<long> Serial_Number { get; set; }
        public string Application_Form_Number { get; set; }
        public string Application_Exam_Number { get; set; }
        public int Application_Form_Setting_Id { get; set; }
        public int Application_Programme_Fee_Id { get; set; }
        public long Payment_Id { get; set; }
        public long Person_Id { get; set; }
        public System.DateTime Date_Submitted { get; set; }
        public bool Release { get; set; }
        public bool Rejected { get; set; }
        public string Reject_Reason { get; set; }
        public string Remarks { get; set; }
        public long Expr1 { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public Nullable<long> Expr2 { get; set; }
        public long Expr3 { get; set; }
        public long Expr4 { get; set; }
        public int Payment_Mode_Id { get; set; }
        public int Payment_Type_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public Nullable<long> Payment_Serial_Number { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Date_Paid { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public int Expr5 { get; set; }
        public string Fee_Type_Name { get; set; }
        public string Fee_Type_Description { get; set; }
        public int Expr6 { get; set; }
        public string Programme_Name { get; set; }
        public string Programme_Description { get; set; }
        public string Programme_Short_Name { get; set; }
        public Nullable<bool> Activated { get; set; }
        public int Expr7 { get; set; }
        public string Department_Name { get; set; }
        public string Department_Code { get; set; }
        public int Faculty_Id { get; set; }
        public int Expr8 { get; set; }
        public int Expr9 { get; set; }
        public int Expr10 { get; set; }
        public int Expr11 { get; set; }
        public int Expr12 { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public System.DateTime Date_Entered { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }
        public string Exam_Venue { get; set; }
        public Nullable<System.TimeSpan> Exam_Time { get; set; }
        public int Expr13 { get; set; }
        public string Session_Name { get; set; }
        public System.DateTime Expr14 { get; set; }
        public System.DateTime Expr15 { get; set; }
        public Nullable<bool> Expr16 { get; set; }
        public decimal Transaction_Amount { get; set; }
        public string Status { get; set; }
        public string RRR { get; set; }
        public System.DateTime Transaction_Date { get; set; }
    }
}
