//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_COURSE_REGISTRATION_SUMMARY
    {
        public string Programme_Name { get; set; }
        public string Department_Name { get; set; }
        public string Level_Name { get; set; }
        public string Session_Name { get; set; }
        public Nullable<int> NUMBER_REGISTERED { get; set; }
        public int Level_Id { get; set; }
        public int Department_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Session_Id { get; set; }
        public int Semester_Id { get; set; }
    }
}
