//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ELEARNING_COURSE_CONTENT
    {
        public long Student_Course_Registration_Detail_Id { get; set; }
        public Nullable<long> Student_Course_Registration_Id { get; set; }
        public long Course_Id { get; set; }
        public int Session_Id { get; set; }
        public int Semester_Id { get; set; }
        public int E_Content_Type_Id { get; set; }
        public Nullable<int> Views { get; set; }
        public string Url { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Level_Id { get; set; }
        public long Person_Id { get; set; }
        public string Programme_Name { get; set; }
        public int Programme_Id { get; set; }
        public string Department_Name { get; set; }
        public int Department_Id { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public bool Active { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Expr1 { get; set; }
        public string Video_Url { get; set; }
        public long Id { get; set; }
    }
}
