//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HOSTEL_ALLOCATION_COUNT
    {
        public long Id { get; set; }
        public long Student_Id { get; set; }
        public int Session_Id { get; set; }
        public int Hostel_Id { get; set; }
        public int Series_Id { get; set; }
        public long Room_Id { get; set; }
        public int Corner_Id { get; set; }
        public bool Occupied { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Level_Id { get; set; }
        public int Hostel_Type_Id { get; set; }
    }
}
