//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HND_APPLICANTS
    {
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Mobile_Phone { get; set; }
        public string Application_Form_Number { get; set; }
        public string Application_Exam_Number { get; set; }
        public string Department_Name { get; set; }
        public string Faculty_Name { get; set; }
        public string Programme_Name { get; set; }
        public string Previous_School_Name { get; set; }
        public string Previous_Course { get; set; }
        public string Level_of_Pass { get; set; }
        public string Sex_Name { get; set; }
    }
}
