//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_OLD_STUDENT
    {
        public long Person_Id { get; set; }
        public string Name { get; set; }
        public string Image_File_Url { get; set; }
        public string Signature_File_Url { get; set; }
        public string Blood_Group_Name { get; set; }
        public string Matric_Number { get; set; }
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public int Programme_Id { get; set; }
        public string Programme_Name { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public Nullable<int> Admitted_Session_Id { get; set; }
        public string Admitted_Session { get; set; }
        public string Application_Form_Number { get; set; }
        public Nullable<int> Admitted_Department_Id { get; set; }
        public string Admitted_Department { get; set; }
        public int Admitted_Programme_Id { get; set; }
        public string Admitted_Programme { get; set; }
        public Nullable<int> Year_Of_Admission { get; set; }
        public Nullable<int> Year_Of_Graduation { get; set; }
        public string Invoice_Number { get; set; }
        public string Confirmation_No { get; set; }
    }
}
