//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_POST_JAMP_APPLICATION
    {
        public long Application_Form_Id { get; set; }
        public long Person_Id { get; set; }
        public int Person_Type_Id { get; set; }
        public string Name { get; set; }
        public string Mobile_Phone { get; set; }
        public long Payment_Id { get; set; }
        public string First_Choice_Department_Name { get; set; }
        public string Image_File_Url { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public string Programme_Name { get; set; }
        public string Application_Form_Number { get; set; }
        public string Application_Exam_Number { get; set; }
        public Nullable<long> Serial_Number { get; set; }
        public Nullable<int> Application_Exam_Serial_Number { get; set; }
    }
}
