//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PAYMENT_CONFIRMATION_NEW_STUDENTS
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int Fee_Type_Id { get; set; }
        public string Invoice_Number { get; set; }
        public System.DateTime Transaction_Date { get; set; }
        public string RRR { get; set; }
        public Nullable<bool> Used { get; set; }
        public decimal Transaction_Amount { get; set; }
        public string Status { get; set; }
        public int Session_Id { get; set; }
        public long Payment_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
    }
}
