//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PAYMENT_NEW_STUDENT_FIRST
    {
        public long Person_Id { get; set; }
        public string Name { get; set; }
        public string Image_File_Url { get; set; }
        public string Signature_File_Url { get; set; }
        public int Admitted_Session_Id { get; set; }
        public string Admitted_Session { get; set; }
        public string Application_Form_Number { get; set; }
        public int Admitted_Department_Id { get; set; }
        public string Admitted_Department { get; set; }
        public int Admitted_Programme_Id { get; set; }
        public string Admitted_Programme { get; set; }
        public int Payment_Mode_Id { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
        public string Confirmation_No { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
    }
}
