//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PAYMENT_VERIFICATION_NEW_STUDENT
    {
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Other_Name { get; set; }
        public string Fee_Type_Name { get; set; }
        public string Payment_Mode_Name { get; set; }
        public System.DateTime DateVerified { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
        public string Expr1 { get; set; }
        public string Confirmation_No { get; set; }
        public string VerificationOfficer { get; set; }
        public string Session_Name { get; set; }
        public string Department_Name { get; set; }
        public string Programme_Name { get; set; }
        public long Person_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public int Payment_Mode_Id { get; set; }
        public string Matric_Number { get; set; }
        public string Application_Form_Number { get; set; }
    }
}
