//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_PAYMENT
    {
        public long Payment_Id { get; set; }
        public string Invoice_Number { get; set; }
        public int Payment_Type_Id { get; set; }
        public string Payment_Type_Name { get; set; }
        public int Payment_Mode_Id { get; set; }
        public string Payment_Mode_Name { get; set; }
        public int Fee_Type_Id { get; set; }
        public string Fee_Type_Name { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
        public Nullable<bool> Activated { get; set; }
        public long Person_Id { get; set; }
        public string Full_Name { get; set; }
        public string Image_File_Url { get; set; }
        public string Mobile_Phone { get; set; }
        public string Matric_Number { get; set; }
        public int Level_Id { get; set; }
        public string Level_Name { get; set; }
        public int Programme_Id { get; set; }
        public string Programme_Name { get; set; }
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public string Bank_Code { get; set; }
        public string Confirmation_No { get; set; }
        public string Receipt_No { get; set; }
        public Nullable<decimal> Transaction_Amount { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
    }
}
