//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SCHOOL_FEES_PAYMENT
    {
        public long Person_Id { get; set; }
        public string Name { get; set; }
        public long Payment_Id { get; set; }
        public string Confirmation_No { get; set; }
        public string Invoice_Number { get; set; }
        public int Fee_Type_Id { get; set; }
        public string Fee_Type_Name { get; set; }
        public int Session_Id { get; set; }
        public string Session_Name { get; set; }
    }
}
