//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_REGISTERED_COURSES_REPORT
    {
        public string Matric_Number { get; set; }
        public string Name { get; set; }
        public long Person_Id { get; set; }
        public int Level_Id { get; set; }
        public int Programme_Id { get; set; }
        public int Department_Id { get; set; }
        public int Session_Id { get; set; }
        public int Semester_Id { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string PROGRAMME_NAME { get; set; }
        public string SESSION_NAME { get; set; }
        public string SEMESTER_NAME { get; set; }
        public string LEVEL_NAME { get; set; }
        public string COURSES_REGISTERED { get; set; }
    }
}
