//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENTS_PAID_BUT_UNREGISTERED
    {
        public string Matric_Number { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public string Session_Name { get; set; }
        public string Invoice_Number { get; set; }
        public string Confirmation_No { get; set; }
        public int Department_Id { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public int Level_Id { get; set; }
        public int Programme_Id { get; set; }
        public long Person_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Other_Name { get; set; }
        public string Name { get; set; }
    }
}
