//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_SCHOOL_FEES_VERIFICATION
    {
        public string Name { get; set; }
        public long Payment_Id { get; set; }
        public int Fee_Type_Id { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public string RRR { get; set; }
        public decimal Transaction_Amount { get; set; }
        public string Department_Name { get; set; }
        public Nullable<int> Faculty_Id { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public System.DateTime DateVerified { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public string Invoice_Number { get; set; }
    }
}
