//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STUDENT_DETAILS
    {
        public long Person_Id { get; set; }
        public string Name { get; set; }
        public string Image_File_Url { get; set; }
        public Nullable<byte> Sex_Id { get; set; }
        public string Sex_Name { get; set; }
        public string Contact_Address { get; set; }
        public string Email { get; set; }
        public string Mobile_Phone { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string State_Id { get; set; }
        public string State_Name { get; set; }
        public string Local_Government_Name { get; set; }
        public Nullable<int> Nationality_Id { get; set; }
        public string Nationality_Name { get; set; }
        public string Home_Town { get; set; }
        public string Home_Address { get; set; }
        public Nullable<int> Religion_Id { get; set; }
        public string Religion_Name { get; set; }
        public string Matric_Number { get; set; }
        public string School_Contact_Address { get; set; }
        public string Genotype_Name { get; set; }
        public string Blood_Group_Name { get; set; }
        public Nullable<int> Programme_Id { get; set; }
        public string Programme_Name { get; set; }
        public string Programme_Short_Name { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public string Department_Code { get; set; }
        public string Department_Name { get; set; }
        public Nullable<int> Level_Id { get; set; }
        public string Level_Name { get; set; }
        public Nullable<int> Session_Id { get; set; }
        public string Session_Name { get; set; }
        public Nullable<int> Faculty_Id { get; set; }
        public string Faculty_Name { get; set; }
        public Nullable<int> Department_Option_Id { get; set; }
        public string Department_Option_Name { get; set; }
    }
}
