//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_UPLOADED_COURSES
    {
        public long Course_Id { get; set; }
        public string Course_Code { get; set; }
        public string Course_Name { get; set; }
        public int Course_Unit { get; set; }
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
        public int Level_Id { get; set; }
        public string Level_Name { get; set; }
        public string Session_Name { get; set; }
        public int Session_Id { get; set; }
        public string Semester_Name { get; set; }
        public int Semester_Id { get; set; }
        public string Faculty_Name { get; set; }
    }
}
