//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_VACANT_BEDSPACES
    {
        public int Hostel_Id { get; set; }
        public string Hostel_Name { get; set; }
        public int Series_Id { get; set; }
        public string Series_Name { get; set; }
        public long Room_Id { get; set; }
        public string Room_Number { get; set; }
        public bool Reserved { get; set; }
        public int Corner_Id { get; set; }
        public string Corner_Name { get; set; }
    }
}
