//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abundance_Nk.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRONG_CARRYOVER
    {
        public Nullable<int> COUNT { get; set; }
        public string COURSE_CODE { get; set; }
        public Nullable<decimal> Exam_Score { get; set; }
        public long Person_Id { get; set; }
        public string Matric_Number { get; set; }
        public long Course_Id { get; set; }
    }
}
